### ISSUE TITLE
Couldn't fetch Service Binding Usages injected in Function "<some function name>" due to this error: Network error: Invariant Violation: 10 (see https://github.com/apollographql/invariant-packages)

### ISSUE THREAD

**Issue by tehret77** [kyma-project/kyma#10377]
**Description**
When open a function that consumes a service binding or event trigger the error 
> Couldn't fetch Service Binding Usages injected in Function "<some function name>" due to this error: Network error: Invariant Violation: 10 (see https://github.com/apollographql/invariant-packages)
is shown.

It happens in all functions that have either one or more event triggers configured or one or more service binding configured.

Kubernetes version: 1.18.10
Cloud Provider: Azure Kubernetes Service
Kyma version: 1.18.0
Browser: Chrome
Client OS: macOS 11.1

**Expected result**

No error message is shown when the browser renders the UI showing a function and configuration.

**Actual result**

Error message:  Couldn't fetch Service Binding Usages injected in Function "<some function name>" due to this error: Network error: Invariant Violation: 10 (see https://github.com/apollographql/invariant-packages) is shown
In the browser console:
```
Uncaught Invariant Violation: Invariant Violation: 10 (see https://github.com/apollographql/invariant-packages)
    at new t (https://core-ui.<cluster domain>/static/js/2.05784562.chunk.js:2:61678)
    at G (https://core-ui.<cluster domain>/static/js/2.05784562.chunk.js:2:279230)
    at e.executeField (https://core-ui.<cluster domain>/static/js/2.05784562.chunk.js:2:278464)
    at https://core-ui.<cluster domain>/static/js/2.05784562.chunk.js:2:276974
    at Array.forEach (<anonymous>)
    at e.executeSelectionSet (https://core-ui.<cluster domain>/static/js/2.05784562.chunk.js:2:276898)
    at https://core-ui.<cluster domain>/static/js/2.05784562.chunk.js:2:274849
    at k (https://core-ui.<cluster domain>/static/js/2.05784562.chunk.js:2:269762)
    at e.withValue (https://core-ui.<cluster domain>/static/js/2.05784562.chunk.js:2:267023)
    at https://core-ui.<cluster domain>/static/js/2.05784562.chunk.js:2:269189
t @ invariant.ts:13
G @ readFromStore.ts:554
e.executeField @ readFromStore.ts:455
(anonymous) @ readFromStore.ts:356
e.executeSelectionSet @ readFromStore.ts:348
(anonymous) @ readFromStore.ts:149
k @ entry.ts:177
e.withValue @ slot.ts:79
(anonymous) @ entry.ts:155
e.recompute @ entry.ts:92
o @ index.ts:112
(anonymous) @ readFromStore.ts:529
e.executeSubSelectedArray @ readFromStore.ts:512
(anonymous) @ readFromStore.ts:169
k @ entry.ts:177
e.withValue @ slot.ts:79
(anonymous) @ entry.ts:155
e.recompute @ entry.ts:92
o @ index.ts:112
e.executeField @ readFromStore.ts:445
(anonymous) @ readFromStore.ts:356
e.executeSelectionSet @ readFromStore.ts:348
(anonymous) @ readFromStore.ts:149
k @ entry.ts:177
e.withValue @ slot.ts:79
(anonymous) @ entry.ts:155
e.recompute @ entry.ts:92
o @ index.ts:112
e.executeField @ readFromStore.ts:472
(anonymous) @ readFromStore.ts:356
e.executeSelectionSet @ readFromStore.ts:348
(anonymous) @ readFromStore.ts:149
k @ entry.ts:177
e.withValue @ slot.ts:79
(anonymous) @ entry.ts:155
e.recompute @ entry.ts:92
o @ index.ts:112
(anonymous) @ readFromStore.ts:529
e.executeSubSelectedArray @ readFromStore.ts:512
(anonymous) @ readFromStore.ts:169
k @ entry.ts:177
e.withValue @ slot.ts:79
(anonymous) @ entry.ts:155
e.recompute @ entry.ts:92
o @ index.ts:112
e.executeField @ readFromStore.ts:445
(anonymous) @ readFromStore.ts:356
e.executeSelectionSet @ readFromStore.ts:348
(anonymous) @ readFromStore.ts:149
k @ entry.ts:177
e.withValue @ slot.ts:79
(anonymous) @ entry.ts:155
e.recompute @ entry.ts:92
o @ index.ts:112
e.executeStoreQuery @ readFromStore.ts:316
(anonymous) @ readFromStore.ts:124
k @ entry.ts:177
e.withValue @ slot.ts:79
(anonymous) @ entry.ts:155
e.recompute @ entry.ts:92
o @ index.ts:112
e.diffQueryAgainstStore @ readFromStore.ts:238
t.diff @ inMemoryCache.ts:221
t.maybeBroadcastWatch @ inMemoryCache.ts:347
(anonymous) @ inMemoryCache.ts:142
o @ index.ts:95
(anonymous) @ inMemoryCache.ts:339
t.broadcastWatches @ inMemoryCache.ts:339
t.write @ inMemoryCache.ts:214
e.markSubscriptionResult @ store.ts:65
(anonymous) @ QueryManager.ts:963
next @ Observable.js:322
b @ Observable.js:135
x @ Observable.js:179
value @ Observable.js:235
(anonymous) @ observables.ts:12
next @ observables.ts:12
b @ Observable.js:135
x @ Observable.js:179
value @ Observable.js:235
next @ index.ts:61
(anonymous) @ client.ts:218
e.processReceivedData @ client.ts:651
client.onmessage @ client.ts:593
setTimeout (async)
m @ Observable.js:64
b @ Observable.js:149
x @ Observable.js:179
value @ Observable.js:240
next @ Observable.js:324
b @ Observable.js:135
x @ Observable.js:179
value @ Observable.js:235
(anonymous) @ observables.ts:12
next @ observables.ts:12
b @ Observable.js:135
x @ Observable.js:179
value @ Observable.js:235
next @ index.ts:61
(anonymous) @ client.ts:218
e.processReceivedData @ client.ts:651
client.onmessage @ client.ts:593
Show 54 more frames
```

**Steps to reproduce**

Configure a function that has one or more service binding or one or more event trigger and open it several times.
The error happens not always when open a function but mainly every second call.

**Troubleshooting**

**Comment by PK85** [comment]
I see it is in review column, please reopen if needed
