### ISSUE TITLE
Commerce Mock test fails on kyma-integration pipeline (Waiting for webservices service class timeout)

### ISSUE THREAD

**Issue by akgalwas** [kyma-project/kyma#10428]
**Description**

The following error occurs on kyma-integration-gardener pipelines:
 ```
1) CommerceMock tests
       CommerceMock test fixture should be ready:
     Error: Waiting for webservices service class timeout (300000 ms)
      at Timeout._onTimeout (utils/index.js:185:89)
      at listOnTimeout (internal/timers.js:554:17)
      at processTimers (internal/timers.js:497:7)

  2) CommerceMock tests
       function should reach Commerce mock API through app gateway:
     Error: Request failed with status code 500
      at createError (node_modules/axios/lib/core/createError.js:16:15)
      at settle (node_modules/axios/lib/core/settle.js:17:12)
      at IncomingMessage.handleStreamEnd (node_modules/axios/lib/adapters/http.js:260:11)
      at endReadableNT (_stream_readable.js:1327:12)
      at processTicksAndRejections (internal/process/task_queues.js:80:21)

  3) CommerceMock tests
       order.created.v1 event should trigger the lastorder function:
     AssertionError: expected { order: {}, event: { data: { orderCode: '789' } } } to have nested property 'event.ce-type'
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:85:41
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async sendEventAndCheckResponse (test/fixtures/commerce-mock/index.js:60:3)
      at async Context.<anonymous> (test/commerce-mock.js:22:5)
```

Exemplary log:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1352225806172033025/build-log.txt

There was also a failure on kyma-integration-k3s pipeline:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3s/1351697353572093952/build-log.txt 

**Expected result**

Test is green

**Comment by pbochynski** [comment]
@polskikiel Is working on it.

**Comment by pbochynski** [comment]
I think it is fixed. Pipeline is green (k3s)
