### ISSUE TITLE
Lambda runs with the undefined environment variable

### ISSUE THREAD

**Issue by crabtree** [kyma-project/kyma#10456]
**Description**

Our test runs revealed that there are some cases when our test lambda executes with the environment variables not fully populated. The log attached below shows that the `process.env.GATEWAY_URL` is undefined.

```
k logs -f -n test lastorder-9wsqr-99f5bcc98-dnqr2 function
URL: undefined/site/orders/789
Function failed to execute: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
::ffff:127.0.0.1 - - [25/Jan/2021:16:09:04 +0000] "POST / HTTP/1.1" 500 21 "-" "axios/0.21.1"
URL: undefined/site/orders/789
::ffff:127.0.0.1 - - [25/Jan/2021:16:09:06 +0000] "POST / HTTP/1.1" 500 21 "-" "axios/0.21.1"
Function failed to execute: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
URL: undefined/site/orders/789
Function failed to execute: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
::ffff:127.0.0.1 - - [25/Jan/2021:16:09:08 +0000] "POST / HTTP/1.1" 500 21 "-" "axios/0.21.1"
URL: undefined/site/orders/789
Function failed to execute: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
::ffff:127.0.0.1 - - [25/Jan/2021:16:09:10 +0000] "POST / HTTP/1.1" 500 21 "-" "axios/0.21.1"
URL: undefined/site/orders/789
Function failed to execute: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
::ffff:127.0.0.1 - - [25/Jan/2021:16:09:12 +0000] "POST / HTTP/1.1" 500 21 "-" "axios/0.21.1"
URL: undefined/site/orders/789
Function failed to execute: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
::ffff:127.0.0.1 - - [25/Jan/2021:16:09:14 +0000] "POST / HTTP/1.1" 500 21 "-" "axios/0.21.1"
URL: undefined/site/orders/789
::ffff:127.0.0.1 - - [25/Jan/2021:16:09:16 +0000] "POST / HTTP/1.1" 500 21 "-" "axios/0.21.1"
Function failed to execute: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
URL: undefined/site/orders/789
Function failed to execute: Error: connect ECONNREFUSED 127.0.0.1:80
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1145:16)
::ffff:127.0.0.1 - - [25/Jan/2021:16:09:18 +0000] "POST / HTTP/1.1" 500 21 "-" "axios/0.21.1"
Shutting down..
Server stopped
```

One of the failed test runs can be found here https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-production-gardener-azure/1353675370502557696/build-log.txt

**Expected result**

The environment variables populated with the correct values.

**Comment by kjaksik** [comment]
It seems that this fail is caused by Application Registry using more CPU than the amount set in the limits. Call to application registry timeouts after 15 seconds because it cannot proccess the request fast enough. After raising the CPU limits a bit to 30 it seems to work every time.

Here's an example top of the app registry pod
```
NAME                                    CPU(cores)   MEMORY(bytes)
application-registry-7568d6bdc4-mglgx   23m          81Mi
```
Here are the limits and requests
```
    Limits:
      cpu:     20m
      memory:  64Mi
    Requests:
      cpu:     10m
      memory:  32Mi
```
