### ISSUE TITLE
Fast integration test of trial clusters fails to deploy a function

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10947]
**Description**

The fast integration test for trial clusters is failing when it tries to deploy a function.

**Expected result**

Function can be deployed and test passes successfully.

**Actual result**

Failure is thrown:
    
      1) SKR test
           CommerceMock test fixture should be ready:
         Error: k8sApply error, cannot create: {"apiVersion":"serverless.kyma-project.io/v1alpha1","kind":"Function","metadata":{"labels":{"serverless.kyma-project.io/build-resources-preset":"local-dev","serverless.kyma-project.io/function-resources-preset":"S","serverless.kyma-project.io/replicas-preset":"S"},"name":"lastorder","namespace":"skr-test"},"spec":{"deps":"{ \"name\": \"orders\", \"version\": \"1.0.0\", \"dependencies\": {\"axios\": \"^0.19.2\"}}","maxReplicas":1,"minReplicas":1,"source":"let lastOrder = {};\nlet lastEvent = {};\nconst axios = require('axios');\nasync function getOrder(code) {\n  let url = findEnv(\"GATEWAY_URL\") + \"/site/orders/\" + code;\n  console.log(\"URL: %s\", url);\n  let response = await axios.get(url, { headers: { \"X-B3-Sampled\": 1 } }).catch((e)=>{\n    return e.response.data;\n  })\n  dump(response);\n  return response.data;\n}\nfunction cloudEventHeaders(event) {\n  return Object.keys(event).reduce((accumulator, current) => {\n    if (current.startsWith('ce-')) {\n      accumulator[current] = event[current]\n    }\n    return accumulator;\n  }, {});\n}\nfunction findEnv(keyPart) {\n  for(let key in process.env) {\n    if(key.indexOf(keyPart) !== -1) {\n      return process.env[key];\n    }\n  }\n  return;\n}\nfunction dump(obj) {\n  console.dir(obj, {depth: null});\n}\nmodule.exports = {\n  main: async function (event, context) {\n    if (event.data && event.data.orderCode) {\n      lastEvent = { ...cloudEventHeaders(event), data: event.data };\n      lastOrder = await getOrder(event.data.orderCode);\n    }\n    return {order:lastOrder, event:lastEvent};\n  }\n}\n"}}
          at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/utils/index.js:269:19
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
          at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/utils/index.js:268:18
          at async Promise.all (index 0)
          at async provisionCommerceMockResources (test/fixtures/commerce-mock/index.js:403:3)
          at async ensureCommerceMockWithCompassTestFixture (test/fixtures/commerce-mock/index.js:304:20)
          at async Context.<anonymous> (skr-test/skr-test.js:61:5)

      2) SKR test
           function should reach Commerce mock API through app gateway:
         Error: Wait for VirtualService commerce-mock timeout (20000 ms)
          at Timeout._onTimeout (utils/index.js:307:18)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)

      3) SKR test
           order.created.v1 event should trigger the lastorder function:
         Error: Wait for VirtualService commerce-mock timeout (20000 ms)
          at Timeout._onTimeout (utils/index.js:307:18)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)

**Steps to reproduce**

See https://storage.googleapis.com/kyma-prow-logs/logs/skr-trial-integration-dev/1373908631224848384/build-log.txt

**Troubleshooting**

Not started yet.

**Comment by tobiscr** [comment]
Temporary issue. Closing this ticket.
