### ISSUE TITLE
Fast integration tests for AWS, Azure and Azure-Lite fail in SKR provisioning step

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10946]
**Description**

The fast-integration test is failing for AWS, Azure and Azure-Lite plans when it tries to provision an SKR cluster.

**Expected result**

Provisioning of an SKr cluster was successful and test cases could be applied.

**Actual result**

Test reports following error message:

      1) SKR test
           Provision SKR:

          AssertionError: expected { Object (state, description) } to have property 'state' of 'succeeded', but got 'failed'      
          actual expected
      
          failedsucceeded
      
          at ensureOperationSucceeded (kyma-environment-broker/helpers.js:50:23)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
          at async provisionSKR (kyma-environment-broker/helpers.js:18:3)
          at async Context.<anonymous> (skr-test/skr-test.js:51:11)

      2) SKR test
       Assign SKR to scenario:
         TypeError: Cannot read property 'shoot' of undefined
          at Context.<anonymous> (skr-test/skr-test.js:57:49)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)

      3) SKR test
           CommerceMock test fixture should be ready:
         Failed to fetch resource metadata for v1/Namespace: connect ECONNREFUSED 127.0.0.1:8080
      Error: connect ECONNREFUSED 127.0.0.1:8080
          at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1146:16)

      4) SKR test
           function should reach Commerce mock API through app gateway:
         Error: Wait for VirtualService commerce-mock timeout (20000 ms)
          at Timeout._onTimeout (utils/index.js:307:18)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)

      5) SKR test
           order.created.v1 event should trigger the lastorder function:
         Error: Wait for VirtualService commerce-mock timeout (20000 ms)
          at Timeout._onTimeout (utils/index.js:307:18)
          at listOnTimeout (internal/timers.js:554:17)
          at processTimers (internal/timers.js:497:7)

**Steps to reproduce**

Consistently failing in Prow, e.g.

https://storage.googleapis.com/kyma-prow-logs/logs/skr-azure-integration-dev/1373138552329605120/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/skr-azure-lite-integration-dev/1373138552333799424/build-log.txt
https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-integration-dev/1373138552333799425/build-log.txt

**Troubleshooting**

Not started yet.

**Comment by tobiscr** [comment]
Update from @crabtree : issue related to changes in KEB. Team is informed already.

**Comment by tobiscr** [comment]
Issue seems to be related to a problems in CLS provisioning.

**Comment by tobiscr** [comment]
Temporary issue. Closing this ticket.
