### ISSUE TITLE
Fast integration test for Trial cluster failed when deprovisioning in Compass

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10953]
**Description**

Fast integration test for Trial cluster failed when deprovisioning in Compass.

**Expected result**

Deprovisioning works and test is passing

**Actual result**

Error is fired:

     /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration /home/prow/go/src/github.com/kyma-project/test-infra
     npm install
     npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@2.1.3 (node_modules/fsevents):
     npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@2.1.3: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

     added 293 packages from 265 contributors and audited 294 packages in 5.871s

     35 packages are looking for funding
       run `npm fund` for details

     found 0 vulnerabilities

     npm run test-skr

     > kyma-js@0.0.1-alpha.12 test-skr /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration
     > mocha --inline-diffs --check-leaks --reporter mocha-multi-reporters --reporter-options configFile=mocha-reporter-config.json ./skr-test/

       SKR test
         ✓ Provision SKR with ID 97ea4563-e3b8-4531-9b25-b71fffe1be2a (2191882ms)
         ✓ Assign SKR to scenario
         ✓ CommerceMock test fixture should be ready (156911ms)
         ✓ function should reach Commerce mock API through app gateway (21081ms)
         ✓ order.created.v1 event should trigger the lastorder function
         ✓ Deprovision SKR (4953961ms)
         1) Unregister SKR resources from Compass

       6 passing (2h)
       1 failing

       1) SKR test
            Unregister SKR resources from Compass:
          Error: Error when updating label definition with key scenarios
           at DirectorClient.updateLabelDefinition (compass/client.js:204:19)
           at runMicrotasks (<anonymous>)
           at processTicksAndRejections (internal/process/task_queues.js:93:5)
           at async removeScenarioFromCompass (compass/helpers.js:11:5)
           at async unregisterKymaFromCompass (compass/fixtures.js:57:3)
           at async Context.<anonymous> (skr-test/skr-test.js:77:5)

**Steps to reproduce**

See https://storage.googleapis.com/kyma-prow-logs/logs/skr-trial-integration-dev/1374195525699506176/build-log.txt

**Troubleshooting**

Not yet started.

**Comment by tobiscr** [comment]
Seems to be temporarily occurring issue. Closing ticket.
