### ISSUE TITLE
Fast integration test for Trail cluster cannot send events from commerce mock caused by timeout

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#10952]
**Description**

The fast integration test for Trial clusters failed caused by a timeout when it tries to send an order from the commerce mock.

**Expected result**

Event could be send and test is passing.

**Actual result**

      SKR test
        ✓ Provision SKR with ID 68411899-990f-4ced-b7fe-4a5cdf2d3e48 (2312098ms)
        ✓ Assign SKR to scenario
        1) CommerceMock test fixture should be ready
        2) function should reach Commerce mock API through app gateway
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    Cannot send event, the response from event gateway:
    ''
    ...
        3) order.created.v1 event should trigger the lastorder function
        ✓ Deprovision SKR (2611730ms)
        ✓ Unregister SKR resources from Compass

      4 passing (1h)
      3 failing

      1) SKR test
           CommerceMock test fixture should be ready:
         Error: Commerce mock local API not available - timeout
        404: Not Found
          at convertAxiosError (utils/index.js:82:10)
          at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:431:15
      at processTicksAndRejections (internal/process/task_queues.js:93:5)
      at async provisionCommerceMockResources (test/fixtures/commerce-mock/index.js:428:3)
      at async ensureCommerceMockWithCompassTestFixture (test/fixtures/commerce-mock/index.js:309:20)
      at async Context.<anonymous> (skr-test/skr-test.js:61:5)

      2) SKR test
           function should reach Commerce mock API through app gateway:
         Error: Function lastorder responded with error
    404: Not Found
          at convertAxiosError (utils/index.js:82:10)
          at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:153:28
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
          at async checkAppGatewayResponse (test/fixtures/commerce-mock/index.js:149:13)
          at async Context.<anonymous> (skr-test/skr-test.js:65:5)

      3) SKR test
           order.created.v1 event should trigger the lastorder function:
         Error: Cannot send event, the response from event gateway
        404: Not Found
          at convertAxiosError (utils/index.js:82:10)
          at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:187:17
          at runMicrotasks (<anonymous>)
          at processTicksAndRejections (internal/process/task_queues.js:93:5)
          at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:168:7
          at async sendEventAndCheckResponse (test/fixtures/commerce-mock/index.js:166:3)
          at async Context.<anonymous> (skr-test/skr-test.js:69:5)

**Steps to reproduce**

See https://storage.googleapis.com/kyma-prow-logs/logs/skr-trial-integration-dev/1374120025933221888/build-log.txt

**Troubleshooting**

As we have currently known issue with KEB provisioning, chance is high that it's just a temporary issue.

**Comment by tobiscr** [comment]
Temporary issue..closing this ticket.
