### ISSUE TITLE
Function deployment is stuck (failed to pull image) on SKR jobs

### ISSUE THREAD

**Issue by adamwalach** [kyma-project/kyma#11436]
**Description**

This problems affects all SKR jobs (example [skr-trial-integration-dev](https://status.build.kyma-project.io/?job=skr-trial-integration-dev)).
Looks like the last green execution was on `2021-06-04 06:06:07 +0000 UTC`.
Jobs are failing with the following error:

```
1) SKR test
       function should reach Commerce mock API through app gateway:
     Error: Function lastorder responded with error
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:87:10)
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:93:28
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkAppGatewayResponse (test/fixtures/commerce-mock/index.js:89:13)
      at async Context.<anonymous> (skr-test/skr-test.js:65:5)
```
This is caused by the `last-order` pod failure:
```
skr-test           lastorder-6fgc4-56997cc7d6-jgb6x                                  1/2     ImagePullBackOff    0          40s
```
Details:
```
Events:
  Type     Reason     Age                From                                                    Message
  ----     ------     ----               ----                                                    -------
  Normal   Scheduled  76s                default-scheduler                                       Successfully assigned skr-test/lastorder-6fgc4-56997cc7d6-jgb6x to ip-10-250-9-205.eu-central-1.compute.internal
  Normal   Created    76s                kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Created container istio-init
  Normal   Started    76s                kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Started container istio-init
  Normal   Pulled     76s                kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Container image "eu.gcr.io/kyma-project/external/istio/proxyv2:1.9.5-distroless" already present on machine
  Normal   Started    75s                kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Started container istio-proxy
  Normal   Pulled     75s                kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Container image "eu.gcr.io/kyma-project/external/istio/proxyv2:1.9.5-distroless" already present on machine
  Normal   Created    75s                kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Created container istio-proxy
  Warning  Failed     74s                kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Failed to pull image "registry.c-892d9c7.kyma-dev.shoot.canary.k8s-hana.ondemand.com/skr-test-lastorder:1204691384b584051a800dcec9bb673705d00b1c61afae0a9eed8ac20c9d1268": rpc error: code = Unknown desc = error pulling image configuration: unknown blob
  Warning  Failed     62s                kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Failed to pull image "registry.c-892d9c7.kyma-dev.shoot.canary.k8s-hana.ondemand.com/skr-test-lastorder:1204691384b584051a800dcec9bb673705d00b1c61afae0a9eed8ac20c9d1268": rpc error: code = Unknown desc = Error response from daemon: error parsing HTTP 404 response body: no error details found in HTTP response body: "{\"error\":{\"code\":404,\"status\":\"Not Found\",\"request\":\"bcbf73e4-08b9-4cf9-a3d9-cb0a99b7c49e\",\"message\":\"The requested resource could not be found\"}}\n"
  Normal   Pulling    37s (x3 over 74s)  kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Pulling image "registry.c-892d9c7.kyma-dev.shoot.canary.k8s-hana.ondemand.com/skr-test-lastorder:1204691384b584051a800dcec9bb673705d00b1c61afae0a9eed8ac20c9d1268"
  Warning  Failed     37s (x3 over 74s)  kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Error: ErrImagePull
  Warning  Failed     37s                kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Failed to pull image "registry.c-892d9c7.kyma-dev.shoot.canary.k8s-hana.ondemand.com/skr-test-lastorder:1204691384b584051a800dcec9bb673705d00b1c61afae0a9eed8ac20c9d1268": rpc error: code = Unknown desc = Error response from daemon: unauthorized: authentication required
  Warning  Failed     9s (x4 over 73s)   kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Error: ImagePullBackOff
  Normal   BackOff    9s (x4 over 73s)   kubelet, ip-10-250-9-205.eu-central-1.compute.internal  Back-off pulling image "registry.c-892d9c7.kyma-dev.shoot.canary.k8s-hana.ondemand.com/skr-test-lastorder:1204691384b584051a800dcec9bb673705d00b1c61afae0a9eed8ac20c9d1268"
  ```

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**

**Comment by kwiatekus** [comment]
This is related to SKR landscape
Closing this one in favor of https://github.tools.sap/kyma/backlog/issues/1550
