### ISSUE TITLE
kyma-integration-hibernation-gardener-azure failing frequently when querying logs from Loki

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/kyma#11941]
**Description**

Job `kyma-integration-hibernation-gardener-azure` succeeds very rarely.
Since this job is testing Kyma on Gardener **with** hibernation and wake-ups and the test failing is using timers, this might be due to Loki not being ready after wake-up.

```kyma-js@0.0.1-alpha.12 test /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration
> mocha --inline-diffs --check-leaks --reporter mocha-multi-reporters --reporter-options configFile=mocha-reporter-config.json
  CommerceMock tests
    ✓ Listing all pods in cluster
    ✓ CommerceMock test fixture should be ready (126727ms)
    ✓ in-cluster event should be delivered
    ✓ function should be reachable through secured API Rule
    ✓ order.created.v1 event should trigger the lastorder function
    ✓ Should print report of restarted containers, skipped if no crashes happened
    1) Logs from commerce mock pod should be retrieved through Loki
    ✓ Test namespaces should be deleted (29286ms)
  Getting Started Guide Tests
    ✓ Listing all pods in cluster
    ✓ Getting started guide fixture should be ready (87207ms)
    ✓ Order should be persisted and should survive pod restarts (redis storage)
    ✓ Should print report of restarted containers, skipped if no crashes happened
    ✓ Namespace should be deleted
  12 passing (6m)
  1 failing
  1) CommerceMock tests
       Logs from commerce mock pod should be retrieved through Loki:
      No logs fetched from Loki      
      actual expected
      
      falsetrue
      
      at checkLokiLogs (logging/helpers.js:21:12)
      at async Context.<anonymous> (test/1-commerce-mock.js:70:5)
```

Find jobs here: https://status.build.kyma-project.io/?job=kyma-integration-hibernation-gardener-azure

**Comment by jeremyharisch** [comment]
I have now checked the pods of Loki when the Kyma is being waked up, after being hibernated. The test waits for all pods in `kyma-system` namespace to have status `RUNNING`. The check is [here](https://github.com/kyma-project/test-infra/blob/main/prow/scripts/lib/gardener/azure.sh#L241).
Thus, this is not due to the reason loki is not ready.
