### ISSUE TITLE
Monitoring tests fail (fast-integration)

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12253]
**Description**
The failing job: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d

Last 5 builds failed with the same reason:
```
  1) Monitoring test
       All Prometheus targets should be healthy:
     AssertionError: Following targets are unhealthy: eventing-controller-metrics: Get "https://10.42.0.10:8080/metrics": read tcp 10.42.0.32:48938->10.42.0.10:8080: read: connection reset by peer, eventing-publisher-proxy-metrics: Get "https://10.42.1.26:9090/metrics": read tcp 10.42.0.32:46874->10.42.1.26:9090: read: connection reset by peer, kiali-server: Get "https://10.42.1.7:9090/metrics": read tcp 10.42.0.32:53498->10.42.1.7:9090: read: connection reset by peer, logging-loki-headless: Get "https://10.42.0.9:3100/metrics": read tcp 10.42.0.32:50716->10.42.0.9:3100: read: connection reset by peer, monitoring-alertmanager: Get "https://10.42.0.30:9093/metrics": http: server gave HTTP response to HTTPS client, monitoring-grafana: Get "https://10.42.1.25:3000/metrics": read tcp 10.42.0.32:45232->10.42.1.25:3000: read: connection reset by peer, service-catalog-addons-service-binding-usage-controller: Get "https://10.42.1.8:8080/metrics": read tcp 10.42.0.32:59452->10.42.1.8:8080: read: connection reset by peer, tracing-jaeger-operator: Get "https://10.42.1.9:8383/metrics": http: server gave HTTP response to HTTPS client, tracing-jaeger-metrics: Get "https://10.42.0.28:14269/metrics": http: server gave HTTP response to HTTPS client: expected [ Array(9) ] to be empty
      at Context.<anonymous> (monitoring-test/monitoring-test.js:54:12)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

  2) Monitoring test
       Metrics used by the Kyma/Function dashboard shoud exist:
     AssertionError: Following queries return no results: topk(10,kube_namespace_labels{label_istio_injection=~"..*"}): expected [ Array(1) ] to be empty
      at assertTimeSeriesExist (monitoring/helpers.js:123:10)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (monitoring-test/monitoring-test.js:124:5)

```

**Comment by pbochynski** [comment]
Should be fixed when https://github.com/kyma-incubator/reconciler/pull/220 will be used in the kyma CLI stable binary.

**Comment by a-thaler** [comment]
First problem fixed by https://github.com/kyma-project/cli/pull/1002
Second problem should be fixed by https://github.com/kyma-project/kyma/pull/12256
