### ISSUE TITLE
Upgrade job from Kyma 1.24 to Kyma 2.0 fails

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12254]
**Description**

The job fails because it uses flag that is removed from CLI:
```
2021/10/01 12:29:49 UTC [INFO] Deploying Kyma
Error: unknown flag: --reuse-values
```

**Expected result**

Job is updated to the latest Kyma CLI syntax

**Actual result**

Failure

**Steps to reproduce**

See the logs: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma-to-kyma2

**Comment by pbochynski** [comment]
Update:
reuse-values flag is removed, but now non-interactive mode doesn't work:
```
2021/10/02 08:33:41 UTC [INFO] ### Installing Kyma 2.0 from main
2021/10/02 08:33:41 UTC [INFO] Deploying Kyma
2021-10-02T08:33:41.491Z	INFO	step/log.go:62	A kyma v1 installation (1.24.6) was found. Please use interactive mode to confirm the upgrade
2021-10-02T08:33:41.491Z	INFO	step/log.go:89	A kyma v1 installation (1.24.6) was found. Do you want to proceed with the upgrade (local)? 
Type [y/N]: Error: Upgrade stopped by user
2021/10/02 08:33:41 UTC [ERROR] AN ERROR OCCURED! Take a look at preceding log entries.
```

**Comment by pbochynski** [comment]
It looks like non-interactive mode works after this fix: https://github.com/kyma-project/cli/pull/1004

**Comment by pbochynski** [comment]
Currently, single test fails after upgrade:
```
  1) Upgrade test tests
       in-cluster event should be delivered:
     AssertionError: The same event id expected in the result: expected { Object (status, statusText, ...) } to have nested property 'data.id'
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:526:37
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkInClusterEventDeliveryHelper (test/fixtures/commerce-mock/index.js:523:3)
      at async checkInClusterEventDelivery (test/fixtures/commerce-mock/index.js:511:3)
      at async Context.<anonymous> (upgrade-test/upgrade-test-tests.js:25:5)
```

**Comment by werdes72** [comment]
@pbochynski It works for me:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/werdes72_test_of_prowjob_kyma-upgrade-gardener-kyma-to-kyma2/1445293233369255936

https://github.com/kyma-project/test-infra/pull/4233

**Comment by pbochynski** [comment]
The job passed twice - the problem should be fixed now.
