### ISSUE TITLE
Preview plan for Kyma 2.0 fails

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12354]
**Description**

The job [kyma-preview-integration-dev](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-preview-integration-dev) fails due to an error in provisioning Kyma with reconciler deployed in the dev environment.

**Expected result**

Installation with reconciler works or at least meaningful error is returned

**Actual result**

```
     Error: the string "operation didn't succeed in 2h: {\"state\":\"failed\",\"description\":\"Operation created : Reconciler failed\"}" was thrown, throw an Error :)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

**Comment by pbochynski** [comment]
Currently, plan fails because the service class is not available:
```
1) SKR test
       CommerceMock test fixture should be ready:
     Error: Waiting for app-1vs8 service class timeout (300000 ms)
      at Timeout._onTimeout (utils/index.js:390:18)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by pbochynski** [comment]
The problem with missing service classes for commerce mock is resolved now:
https://storage.googleapis.com/kyma-prow-logs/logs/kyma-preview-integration-dev/1455686308339912704/build-log.txt
Now deprovisioning is an issue.

**Comment by pbochynski** [comment]
Deletion is not enabled yet in the reconciler. Still, istio and ory components do not have delete operation implemented.

**Comment by pbochynski** [comment]
Some tests fail with passing initial admin of the runtime. @kwiatekus and @PK85 are working on it.

**Comment by pbochynski** [comment]
It seems to work now.
