### ISSUE TITLE
skr-kyma-to-kyma2-upgrade-aws-dev fails

### ISSUE THREAD

**Issue by k15r** [kyma-project/kyma#12479]
The kyma to kyma2 upgrade job fails constantly with these erors:

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-kyma-to-kyma2-upgrade-aws-dev

Errors:

Phase 1:
```sh
Running kcpLogin...
Error: Command failed with exit code 1: kcp login --config dev.yaml -u sap.cp.xf.kyma.test@sap.com -p ****
Error: authentication error: ropc error: resource owner password credentials flow error: resource owner password credentials flow error: oauth2: cannot fetch token: 400 
Response: {"error":"invalid_grant","error_description":"User authentication failed: INITIAL_PASSWORD_EXPIRED"}
    at makeError (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async kcpLogin (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-kyma-to-kyma2-upgrade/upgrade-helpers.js:13:22)
    at async Context.<anonymous> (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js:190:23) {
  shortMessage: 'Command failed with exit code 1: kcp login --config dev.yaml -u sap.cp.xf.kyma.test@sap.com -p XO4RStMsba9eUE5l',
  command: 'kcp login --config dev.yaml -u sap.cp.xf.kyma.test@sap.com -p XO4RStMsba9eUE5l',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Error: authentication error: ropc error: resource owner password credentials flow error: resource owner password credentials flow error: oauth2: cannot fetch token: 400 \n' +
    'Response: {"error":"invalid_grant","error_description":"User authentication failed: INITIAL_PASSWORD_EXPIRED"}',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
    1) Perform kcp login
Running kcpUpgrade...
Error: Command failed with exit code 1: kcp upgrade kyma --config dev.yaml --version "release-2.0-2d76aa8" --target subaccount=c06f8934-f25f-4146-99ce-a42932c812f6,runtime-id=0331fc12-df67-4df4-91a6-727309db89a4
Error: while triggering kyma upgrade: while calling kyma upgrade operation: while calling https://kyma-env-broker.cp.dev.kyma.cloud.sap/upgrade/kyma: Post "https://kyma-env-broker.cp.dev.kyma.cloud.sap/upgrade/kyma": authentication error: authcode-browser error: authentication error: authorization code flow error: oauth2 error: authorization error: authorization error: context deadline exceeded
    at makeError (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/execa/lib/error.js:59:11)
    at handlePromise (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/execa/index.js:114:26)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async kcpUpgrade (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-kyma-to-kyma2-upgrade/upgrade-helpers.js:31:22)
    at async Context.<anonymous> (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js:195:28) {
  shortMessage: 'Command failed with exit code 1: kcp upgrade kyma --config dev.yaml --version "release-2.0-2d76aa8" --target subaccount=c06f8934-f25f-4146-99ce-a42932c812f6,runtime-id=0331fc12-df67-4df4-91a6-727309db89a4',
  command: 'kcp upgrade kyma --config dev.yaml --version "release-2.0-2d76aa8" --target subaccount=c06f8934-f25f-4146-99ce-a42932c812f6,runtime-id=0331fc12-df67-4df4-91a6-727309db89a4',
  exitCode: 1,
  signal: undefined,
  signalDescription: undefined,
  stdout: '',
  stderr: 'Error: while triggering kyma upgrade: while calling kyma upgrade operation: while calling https://kyma-env-broker.cp.dev.kyma.cloud.sap/upgrade/kyma: Post "https://kyma-env-broker.cp.dev.kyma.cloud.sap/upgrade/kyma": authentication error: authcode-browser error: authentication error: authorization code flow error: oauth2 error: authorization error: authorization error: context deadline exceeded',
  failed: true,
  timedOut: false,
  isCanceled: false,
  killed: false
}
```

Phase2:
```sh
  1) SKR-Upgrade-test
       Perform kcp login:
     TypeError: debug.log is not a function
      at kcpLogin (skr-kyma-to-kyma2-upgrade/upgrade-helpers.js:18:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-kyma-to-kyma2-upgrade/index.js:190:23)

  2) SKR-Upgrade-test
       Perform Upgrade:
     Error: failed "kcp upgrade kyma --config dev.yaml --version "release-2.0-2d76aa8" --target subaccount=c06f8934-f25f-4146-99ce-a42932c812f6,runtime-id=0331fc12-df67-4df4-91a6-727309db89a4": Error: while triggering kyma upgrade: while calling kyma upgrade operation: while calling https://kyma-env-broker.cp.dev.kyma.cloud.sap/upgrade/kyma: Post "https://kyma-env-broker.cp.dev.kyma.cloud.sap/upgrade/kyma": authentication error: authcode-browser error: authentication error: authorization code flow error: oauth2 error: authorization error: authorization error: context deadline exceeded
      at kcpUpgrade (skr-kyma-to-kyma2-upgrade/upgrade-helpers.js:44:15)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-kyma-to-kyma2-upgrade/index.js:195:28)
```

**Comment by kwiatekus** [comment]
Problem fixed
