### ISSUE TITLE
Upgrade test fails - skr-kyma-to-kyma2-upgrade-aws-dev

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12582]
**Description**
Job https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-kyma-to-kyma2-upgrade-aws-dev fails:

```
  1) SKR-Upgrade-test
       Perform Upgrade:
     Error: failed during upgradeKyma
      at KCPWrapper.upgradeKyma (kcp/client.js:117:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-kyma-to-kyma2-upgrade/index.js:196:28)
```

Upgrade fails with timeout and reports no operation in the orchestration:
```
OrchestrationID: 2231f7ec-7a36-4232-b07e-6a8ccc440181
Waiting for Kyma Upgrade with OrchestrationID 2231f7ec-7a36-4232-b07e-6a8ccc440181 to succeed...
OrchestrationID: 2231f7ec-7a36-4232-b07e-6a8ccc440181 (upgradeKyma to version "2.0.0-rc4"), status: failed
No operations in OrchestrationID 2231f7ec-7a36-4232-b07e-6a8ccc440181
....
wait timeout
```

**Comment by varbanv** [comment]
Upgrade still fails with 2 errors the logs have no additional errors listed besides a 502 response to a compass call.
```
1) SKR-Upgrade-test
       Perform Upgrade:
     Error: failed during upgradeKyma
      at KCPWrapper.upgradeKyma (kcp/client.js:117:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-kyma-to-kyma2-upgrade/index.js:196:28)

  2) SKR-Upgrade-test
       Unregister Kyma resources from Compass:
     Error: Error when deleting label scenarios from application 4f6c7432-3f96-46a9-aba7-b929a615d9db: Error: Error calling Director API: 502 Bad Gateway
      at DirectorClient.deleteApplicationLabel (compass/client.js:246:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async removeApplicationFromScenario (compass/helpers.js:75:16)
      at async unregisterKymaFromCompass (compass/fixtures.js:44:5)
      at async Context.<anonymous> (skr-kyma-to-kyma2-upgrade/index.js:235:7)
```
```
url: 'https://compass-gateway-auth-oauth.mps.dev.kyma.cloud.sap/director/graphql',
    method: 'post',
    data: '{"query":"mutation { result: deleteApplicationLabel(applicationID: \\"4f6c7432-3f96-46a9-aba7-b929a615d9db\\", key: \\"scenarios\\") { key value } }"}',
```

**Comment by pbochynski** [comment]
The current failure is not well logged:
```
  1) SKR-Upgrade-test
       Perform Upgrade:
     Error: failed during upgradeKyma
      at KCPWrapper.upgradeKyma (kcp/client.js:117:19)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-kyma-to-kyma2-upgrade/index.js:196:28)
```
@ksputo @suleymanakbas91  Can you check what to do to have better logs?

**Comment by ksputo** [comment]
Found the missing piece, added it to the upgradeKyma queue changes:

https://github.com/kyma-project/control-plane/pull/1066/files#diff-0dca98dbad8b61492422a3b7965a2204763ada3e38033acf9b7a7a37ad8573a3R44

**Comment by ksputo** [comment]
> The current failure is not well logged:
> 
> ```
>   1) SKR-Upgrade-test
>        Perform Upgrade:
>      Error: failed during upgradeKyma
>       at KCPWrapper.upgradeKyma (kcp/client.js:117:19)
>       at runMicrotasks (<anonymous>)
>       at processTicksAndRejections (internal/process/task_queues.js:95:5)
>       at async Context.<anonymous> (skr-kyma-to-kyma2-upgrade/index.js:196:28)
> ```
> 
> @ksputo @suleymanakbas91 Can you check what to do to have better logs?

there were some changes introduced to provide more detailed info about failures:
https://github.com/kyma-project/kyma/pull/12636

**Comment by ksputo** [comment]
As this issue serves as umbrella issue and it's goal is to fix all 1.x->2.0 upgrade issues on the SKR, right now we're working on this one:
```
            {
              state: 'failed',
              description: 'invalid operation data - cannot create cluster configuration',
              createdAt: '2021-11-23T08:32:29.582631Z',
              operationID: '7e38a88a-84ce-47cd-8256-fda029a5b7b5',
              orchestrationID: 'eee4c962-d936-41e8-a3fd-ea244a068d19'
            }
```

**Comment by ksputo** [comment]
![image](https://user-images.githubusercontent.com/26189888/143406997-53fd046a-c64b-4128-887e-0355b99b133e.png)
