### ISSUE TITLE
kyma-integration-k3d job fails - commerce mock can't connect to connector service

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12600]
**Description**
Commerce mock can't connect to Kyma (connector service)

```
  1) CommerceMock tests
       CommerceMock test fixture should be ready:
     Error: Error during establishing connection from Commerce Mock to Kyma connector service
500: Internal Server Error: {"error":"Error: connect ECONNREFUSED 127.0.0.1:443"}
      at convertAxiosError (utils/index.js:92:10)
      at connectCommerceMock (test/fixtures/commerce-mock/index.js:374:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async connectMockLocal (test/fixtures/commerce-mock/index.js:336:3)
      at async ensureCommerceMockLocalTestFixture (test/fixtures/commerce-mock/index.js:448:3)
      at async Context.<anonymous> (test/1-commerce-mock.js:45:5)
```

**Actual result**

https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d

**Comment by pbochynski** [comment]
Fixed by reverting k3d from 5.1 to 4.x
