### ISSUE TITLE
CommerceMock tests on Kyma Open Source fail with latest version of application-gateway 

### ISSUE THREAD

**Issue by koala7659** [kyma-project/kyma#12617]
**Description**

After updating the image on `application-gateway` component in `values.yaml` file from version `PR-12181` to the latest one `4a206dab` I noticed that Fast Integration does not pass anymore. 

Additionally on prow following related jobs fail.

- pre-main-kyma-gardener-azure-alpha-eval
- pre-main-kyma-gardener-azure-alpha-prod
- pre-main-kyma-integration-k3d
- pre-main-kyma-integration-k3d-compass-dev

It is highly probably that we introduced regression in this component between versions `PR-12181` and `4a206dab`

Expected result
**All fast integration tests passed.**

Actual result

```
1) CommerceMock tests
       function should be reachable through secured API Rule:
     AssertionError: expected { event: {}, podName: 'lastorder-pl64l-57c6bcb96d-djzn7' } to have nested property 'order.totalPriceWithTax.value'
      at checkFunctionResponse (test/fixtures/commerce-mock/index.js:133:35)
      at processTicksAndRejections (node:internal/process/task_queues:96:5)
      at async Context.<anonymous> (test/1-commerce-mock.js:56:5)
```

**Comment by koala7659** [comment]
Problem most likely caused by code change delivered in https://github.com/kyma-project/kyma/pull/12074/files

**Comment by koala7659** [comment]
PR reversing changes from #12074 seems to work fine: https://github.com/kyma-project/kyma/pull/12625
