### ISSUE TITLE
SVCAT Migration fast-integration test fails talking to service manager

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/kyma#12757]
**Description**

https://status.build.kyma-project.io/?job=skr-aws-svcat-migration-dev
```
  1) SKR SVCAT migration test
       Should provision new ServiceManager platform:
     Error: failed "smctl login -a https://service-manager.cfapps.sap.hana.ondemand.com --param subdomain=e2etestingscmigration --auth-flow client-credentials": Error: Could not get Service Manager info
Reason: request GET https://service-manager.cfapps.sap.hana.ondemand.com/v1/info?subdomain=e2etestingscmigration failed: StatusCode: 502 Body: 502 Bad Gateway: Registered endpoint failed to handle the request.

      at Object.provisionPlatform (skr-svcat-migration-test/test-helpers.js:202:15)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-svcat-migration-test/skr-svcat-migration-test.js:44:21)
```

**Comment by wozniakjan** [comment]
currently, there is a series of outages in the service manager, provisioner and director, preventing the successful execution of the tests. They are being resolved by particular teams. I will keep monitoring the progress there.

**Comment by wozniakjan** [comment]
both outages are resolved, pipeline back to green for the past 12 hours
