### ISSUE TITLE
Rewrite kyma2 upgrade and svcat migration tests

### ISSUE THREAD

**Issue by wozniakjan** [kyma-project/kyma#12892]
**Description**

https://github.com/kyma-project/kyma/pull/12869 has removed a bunch of code so now these tests are failing to even interpret javascript code because of missing imports
* kyma2 upgrade: https://storage.googleapis.com/kyma-prow-logs/logs/skr-kyma-to-kyma2-upgrade-aws-dev/1471691794696638464/build-log.txt
* svcat migration: https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-svcat-migration-dev/1471691794734387200/build-log.txt

These tests will need to be rewritten.

**Expected result**

tests to pass

**Actual result**

tests failing with
```
Error: Cannot find module '../installer/helm'
Require stack:
- /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-svcat-migration-test/test-helpers.js
- /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js
- /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/esm-utils.js
- /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/mocha.js
- /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/cli/one-and-dones.js
- /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/cli/options.js
- /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/bin/mocha
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
    at Function.Module._load (internal/modules/cjs/loader.js:746:27)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-svcat-migration-test/test-helpers.js:1:19)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.<anonymous> (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js:49:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.exports.requireOrImport (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/esm-utils.js:42:12)
    at Object.exports.loadFilesAsync (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/esm-utils.js:55:34)
    at Mocha.loadFilesAsync (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/mocha.js:473:19)
    at singleRun (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/cli/run-helpers.js:125:15)
    at exports.runMocha (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/cli/run-helpers.js:190:10)
    at Object.exports.handler (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/mocha/lib/cli/run.js:362:11)
    at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/node_modules/yargs/build/index.cjs:443:71
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fast-integration-tests@0.0.1-alpha.12 test-skr-kyma-to-kyma2-upgrade: `mocha --inline-diffs --check-leaks --reporter mocha-multi-reporters --reporter-options configFile=mocha-reporter-config.json ./skr-kyma-to-kyma2-upgrade/index.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fast-integration-tests@0.0.1-alpha.12 test-skr-kyma-to-kyma2-upgrade script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Steps to reproduce**

n/a

**Troubleshooting**

n/a

**Comment by ksputo** [comment]
fixed in #12898
