### ISSUE TITLE
skr-kyma-to-kyma2-upgrade-aws-dev fails with timeout

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#12981]
**Description**
[skr-kyma-to-kyma2-upgrade-aws-dev](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-kyma-to-kyma2-upgrade-aws-dev) job fails with timeout on upgrade and deprovision.

Upgrade timeout:
```
OrchestrationID: d976fca5-4d48-468b-a608-852cdd66b320
Waiting for Kyma Upgrade with OrchestrationID d976fca5-4d48-468b-a608-852cdd66b320 to succeed...
OrchestrationID: d976fca5-4d48-468b-a608-852cdd66b320 (upgradeKyma to version 2.0.0), status: in progress
OrchestrationID: d976fca5-4d48-468b-a608-852cdd66b320: OperationID: 6eac180d-9444-4862-bfdb-7624aa50ab08: OperationStatus: in progress
...
OperationStatus: in progress
OrchestrationID: d976fca5-4d48-468b-a608-852cdd66b320 (upgradeKyma to version 2.0.0), status: in progress
OrchestrationID: d976fca5-4d48-468b-a608-852cdd66b320: OperationID: 6eac180d-9444-4862-bfdb-7624aa50ab08: OperationStatus: in progress
wait timeout
Error: wait timeout
    at Timeout.<anonymous> (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/utils/index.js:1201:20)
    at listOnTimeout (internal/timers.js:557:17)
    at processTimers (internal/timers.js:500:7)
Error: failed during ensureOrchestrationSucceeded
    at KCPWrapper.ensureOrchestrationSucceeded (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/kcp/client.js:240:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async KCPWrapper.upgradeKyma (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/kcp/client.js:117:43)
    at async Context.<anonymous> (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js:205:28)
ReferenceError: subaccount is not defined
    at KCPWrapper.upgradeKyma (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/kcp/client.js:124:64)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Context.<anonymous> (/home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/skr-kyma-to-kyma2-upgrade/index.js:205:28)
OrchestrationID: d976fca5-4d48-468b-a608-852cdd66b320 (upgradeKyma to version 2.0.0), status: in progress
OrchestrationID: d976fca5-4d48-468b-a608-852cdd66b320: OperationID: 6eac180d-9444-4862-bfdb-7624aa50ab08: OperationStatus: in progress
Orchestration Status: {
  orchestrationID: 'd976fca5-4d48-468b-a608-852cdd66b320',
  type: 'upgradeKyma',
  state: 'in progress',
  description: 'Scheduled 1 operations',
  createdAt: '2022-01-04T08:34:29.964983Z',
  updatedAt: '2022-01-04T08:34:29.964983Z',
  parameters: {
    targets: {
      include: [ { instanceID: '58bebe31-290b-4f2c-92b0-fffa431bad02' } ]
    },
    strategy: {
      type: 'parallel',
      schedule: 'immediate',
      parallel: { workers: 1 }
    },
    kubernetes: {
      kubernetesVersion: '1.20.11',
      machineImage: '',
      machineImageVersion: ''
    },
    kyma: { version: '2.0.0' }
  },
  operationStats: { 'in progress': 1 }
}
Operations: {
  data: [
    {
      operationID: '6eac180d-9444-4862-bfdb-7624aa50ab08',
      runtimeID: '083818e4-d9c2-4c2a-8372-3a931955ffac',
      globalAccountID: 'e449f875-b5b2-4485-b7c0-98725c0571bf',
      subAccountID: 'prow-keb-integration',
      orchestrationID: 'd976fca5-4d48-468b-a608-852cdd66b320',
      servicePlanID: '361c511f-f939-4621-b228-d0fb79a1fe15',
      servicePlanName: 'aws',
      dryRun: false,
      shootName: 'c-903cf35',
      maintenanceWindowBegin: '0001-01-01T00:00:00Z',
      maintenanceWindowEnd: '0001-01-01T00:00:00Z',
      state: 'in progress',
      description: 'Operation created'
    }
  ],
  count: 1,
  totalCount: 1
}
Kyma Upgrade failed
    1) Perform Upgrade

Runtime status: {
	"data": [
		{
			"instanceID": "58bebe31-290b-4f2c-92b0-fffa431bad02",
			"runtimeID": "083818e4-d9c2-4c2a-8372-3a931955ffac",
			"globalAccountID": "e449f875-b5b2-4485-b7c0-98725c0571bf",
			"subAccountID": "prow-keb-integration",
			"region": "eu-central-1",
			"subAccountRegion": "cf-eu10",
			"shootName": "c-903cf35",
			"serviceClassID": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
			"serviceClassName": "kymaruntime",
			"servicePlanID": "361c511f-f939-4621-b228-d0fb79a1fe15",
			"servicePlanName": "aws",
			"provider": "AWS",
			"status": {
				"createdAt": "2022-01-04T08:01:35.947572Z",
				"modifiedAt": "2022-01-04T08:34:32.647655Z",
				"state": "upgrading",
				"provisioning": {
					"state": "succeeded",
					"description": "Operation created",
					"createdAt": "2022-01-04T08:01:35.942835Z",
					"operationID": "550840c2-4415-414c-b7b9-8d80e406cd05"
				},
				"upgradingKyma": {
					"data": [
						{
							"state": "in progress",
							"description": "Operation created",
							"createdAt": "2022-01-04T08:34:32.358014Z",
							"operationID": "6eac180d-9444-4862-bfdb-7624aa50ab08",
							"orchestrationID": "d976fca5-4d48-468b-a608-852cdd66b320"
						}
					],
					"totalCount": 1,
					"count": 1
				}
			},
			"userID": "test@test.com",
			"avsInternalEvaluationID": 162823301
		}
	],
	"count": 1,
	"totalCount": 1
}
```

Deprovisioning timeout:
```
  2) SKR-Upgrade-test
       Deprovision SKR:
     Error: the string "Error: wait timeout\nRuntime status: {\n\t\"data\": [\n\t\t{\n\t\t\t\"instanceID\": \"58bebe31-290b-4f2c-92b0-fffa431bad02\",\n\t\t\t\"runtimeID\": \"083818e4-d9c2-4c2a-8372-3a931955ffac\",\n\t\t\t\"globalAccountID\": \"e449f875-b5b2-4485-b7c0-98725c0571bf\",\n\t\t\t\"subAccountID\": \"prow-keb-integration\",\n\t\t\t\"region\": \"eu-central-1\",\n\t\t\t\"subAccountRegion\": \"cf-eu10\",\n\t\t\t\"shootName\": \"c-903cf35\",\n\t\t\t\"serviceClassID\": \"47c9dcbf-ff30-448e-ab36-d3bad66ba281\",\n\t\t\t\"serviceClassName\": \"kymaruntime\",\n\t\t\t\"servicePlanID\": \"361c511f-f939-4621-b228-d0fb79a1fe15\",\n\t\t\t\"servicePlanName\": \"aws\",\n\t\t\t\"provider\": \"AWS\",\n\t\t\t\"status\": {\n\t\t\t\t\"createdAt\": \"2022-01-04T08:01:35.947572Z\",\n\t\t\t\t\"modifiedAt\": \"2022-01-04T09:19:24.230936Z\",\n\t\t\t\t\"state\": \"deprovisioning\",\n\t\t\t\t\"provisioning\": {\n\t\t\t\t\t\"state\": \"succeeded\",\n\t\t\t\t\t\"description\": \"Operation created\",\n\t\t\t\t\t\"createdAt\": \"2022-01-04T08:01:35.942835Z\",\n\t\t\t\t\t\"operationID\": \"550840c2-4415-414c-b7b9-8d80e406cd05\"\n\t\t\t\t},\n\t\t\t\t\"deprovisioning\": {\n\t\t\t\t\t\"state\": \"in progress\",\n\t\t\t\t\t\"description\": \"Operation created\",\n\t\t\t\t\t\"createdAt\": \"2022-01-04T08:50:15.27981Z\",\n\t\t\t\t\t\"operationID\": \"9e65feaa-1657-4bbe-9a93-98d8d0bb2153\"\n\t\t\t\t},\n\t\t\t\t\"upgradingKyma\": {\n\t\t\t\t\t\"data\": [\n\t\t\t\t\t\t{\n\t\t\t\t\t\t\t\"state\": \"failed\",\n\t\t\t\t\t\t\t\"description\": \"operation has reached the time limit: 15m0s\",\n\t\t\t\t\t\t\t\"createdAt\": \"2022-01-04T08:34:32.358014Z\",\n\t\t\t\t\t\t\t\"operationID\": \"6eac180d-9444-4862-bfdb-7624aa50ab08\",\n\t\t\t\t\t\t\t\"orchestrationID\": \"d976fca5-4d48-468b-a608-852cdd66b320\"\n\t\t\t\t\t\t}\n\t\t\t\t\t],\n\t\t\t\t\t\"totalCount\": 1,\n\t\t\t\t\t\"count\": 1\n\t\t\t\t}\n\t\t\t},\n\t\t\t\"userID\": \"test@test.com\",\n\t\t\t\"avsInternalEvaluationID\": 162823301\n\t\t}\n\t],\n\t\"count\": 1,\n\t\"totalCount\": 1\n}" was thrown, throw an Error :)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)

```

**Comment by tobiscr** [comment]
We increased the timeout right now, and see if it still happens with a much bigger timeout

**Comment by ruanxin** [comment]
by looking at the pods status in cluster for this upgrade job, the monitoring-auth-proxy-grafana pod always end up into CrashLoopBackOff
```
kyma-installer     kyma-installer-78c8675956-9jpt4                                   1/1     Running            0          32m
kyma-integration   application-broker-ff8b69b77-bztl6                                2/2     Running            0          3m41s
kyma-integration   application-operator-0                                            1/1     Running            0          3m35s
kyma-system        alertmanager-monitoring-alertmanager-0                            2/2     Running            0          2m42s
kyma-system        api-gateway-84788d449-68vvk                                       1/1     Running            0          3m56s
kyma-system        apiserver-proxy-77d75f6ccb-tk7t6                                  2/2     Running            0          25m
kyma-system        busola-migrator-79778f9b98-5wwdp                                  2/2     Running            0          3m57s
kyma-system        central-application-connectivity-validator-77f7dfbcb5-k62qj       2/2     Running            0          3m41s
kyma-system        central-application-gateway-6987cfd778-r6swv                      2/2     Running            0          3m41s
kyma-system        cluster-essentials-pod-preset-webhook-544d6df8d4-dhgqv            1/1     Running            0          5m24s
kyma-system        cluster-essentials-pod-preset-webhook-544d6df8d4-fxz98            1/1     Running            0          5m27s
kyma-system        console-backend-7c475fc9d8-vtdnk                                  2/2     Running            0          21m
kyma-system        console-web-749dbfddb7-7txw5                                      2/2     Running            0          21m
kyma-system        dex-7bbbb5f88f-lvczk                                              2/2     Running            0          20m
kyma-system        eventing-controller-759c7658f6-xjldk                              2/2     Running            2          3m41s
kyma-system        eventing-nats-0                                                   1/1     Running            0          3m41s
kyma-system        eventing-nats-1                                                   1/1     Running            0          3m16s
kyma-system        eventing-nats-2                                                   1/1     Running            0          3m3s
kyma-system        eventing-publisher-proxy-796b46b657-t4kx9                         2/2     Running            0          3m5s
kyma-system        helm-broker-79754c449c-vtwp6                                      3/3     Running            0          3m11s
kyma-system        helm-broker-addons-ui-7d5bf4cfc8-4n5mf                            1/1     Running            0          27m
kyma-system        helm-broker-etcd-stateful-0                                       1/1     Running            0          27m
kyma-system        helm-broker-webhook-5b796db69c-kh46h                              1/1     Running            0          3m43s
kyma-system        iam-kubeconfig-service-758676f6cd-s4rkb                           2/2     Running            0          24m
kyma-system        logging-fluent-bit-6vx2m                                          2/2     Running            0          3m13s
kyma-system        logging-fluent-bit-h6gmj                                          2/2     Running            0          2m26s
kyma-system        logging-log-ui-6d85b9f855-t9dbm                                   1/1     Running            0          26m
kyma-system        logging-loki-0                                                    2/2     Running            0          3m16s
kyma-system        monitoring-auth-proxy-grafana-6d9b684799-hzgx5                    1/2     CrashLoopBackOff   5          3m26s
kyma-system        monitoring-auth-proxy-grafana-97cf58656-fffwh                     2/2     Running            0          22m
kyma-system        monitoring-grafana-86ccd9ff9b-5mgqq                               5/5     Running            0          3m25s
kyma-system        monitoring-kube-state-metrics-7bdd4f5dd9-r4xkx                    1/1     Running            0          22m
kyma-system        monitoring-operator-69786f5bb9-dmrrf                              1/1     Running            0          3m26s
kyma-system        monitoring-prometheus-istio-server-6799566b98-fgfhr               2/2     Running            0          3m26s
kyma-system        monitoring-prometheus-node-exporter-lszp9                         1/1     Running            0          3m24s
kyma-system        monitoring-prometheus-node-exporter-wq7zg                         1/1     Running            0          3m14s
kyma-system        ory-hydra-5d4b766967-r8stb                                        2/2     Running            0          3m45s
kyma-system        ory-hydra-maester-5dc66cc5bf-jbxqd                                3/3     Running            0          3m45s
kyma-system        ory-oathkeeper-56b984d69-8jb85                                    3/3     Running            0          2m42s
kyma-system        ory-oathkeeper-56b984d69-99z96                                    3/3     Running            0          10

**Comment by ruanxin** [comment]
I assume it related to this issue https://github.com/kyma-incubator/reconciler/issues/650

**Comment by tobiscr** [comment]
@jeremyharisch reported that the pipeline is now failing by Gardner caused by non-deleted CRs:

     retry failed with context deadline exceeded, last error: remaining objects are still present: [*v1.CustomResourceDefinition /applications.applicationconnector.kyma-project.io *v1.CustomResourceDefinition /clusterassets.rafter.kyma-project.io *v1.CustomResourceDefinition /clusterbuckets.rafter.kyma-project.io *v1.CustomResourceDefinition /clusterservicebrokers.servicecatalog.k8s.io *v1.CustomResourceDefinition /oauth2clients.hydra.ory.sh *v1.CustomResourceDefinition /servicebindings.servicecatalog.k8s.io *v1.CustomResourceDefinition /serviceinstances.servicecatalog.k8s.io *v1.CustomResourceDefinition /usagekinds.servicecatalog.kyma-project.io]
