### ISSUE TITLE
OAuth fails on upgrade integration tests

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#12996]
**Description**
The fast integration tests fail often due to a failing OAuth request:

```
  1) Upgrade test tests
       function should be reachable through secured API Rule:
     Error: Error when requesting bearer token from https://oauth2.grdi038e3.kyma-prow.shoot.canary.k8s-hana.ondemand.com/oauth2/token: 401 Unauthorized
      at OAuthToken.getToken (lib/oauth.js:69:27)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkFunctionResponse (test/fixtures/commerce-mock/index.js:128:23)
      at async Context.<anonymous> (upgrade-test/upgrade-test-tests.js:29:5)
```
**Expected result**

OAuth request is retried until successful.

**Actual result**

If the request does not work immediately the tests fail.

**Steps to reproduce**

Run a reconciler kyma1 -> kyma2 upgrade and then the upgrade tests

**Troubleshooting**
See related job:
https://storage.googleapis.com/kyma-prow-logs/logs/periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade/1478652595215011840/build-log.txt

**Comment by cnvergence** [comment]
Waiting for the bumps https://github.com/kyma-project/cli/pull/1132 and https://github.com/kyma-project/control-plane/pull/1244

**Comment by Tomasz-Smelcerz-SAP** [comment]
I have found there aren't any retries in some OAuth-related functions. Maybe retrying at least once would help to mitigate the issue? It still doesn't explain why 401 are returned, but at least it would be a step towards fixing that problem.

**Comment by pbochynski** [comment]
Today again 2 consecutive executions failed due to 401 errors returned from the get token request:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade/1480766581515489281
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/periodic-main-kyma-incubator-reconciler-kyma1-kyma2-upgrade/1480796780793696256

**Comment by cnvergence** [comment]
After implementing Hydra rollout adjustments, the success rate was improved, although we have noticed this issue again today. Currently we are investigating this and creating new PR for the hydra-maester sync https://github.com/kyma-incubator/reconciler/pull/661

**Comment by pbochynski** [comment]
It looks like it doesn't appear any more.
