### ISSUE TITLE
SKR jobs fail: kcp gets 401 error from KEB

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#13311]
**Description**
Many SKR jobs fail with such error:
```  
1) Execute SKR test
       "before all" hook: Provision SKR in "Execute SKR test":
     Error: before hook failed: Error: kcp command failed: Error: while listing runtimes: calling https://kyma-env-broker.cp.dev.kyma.cloud.sap/runtimes?instance_id=a2f9021c-6dd1-4596-b674-d53ebdf0ded0&op_detail=all&page=1&page_size=100 returned 401 (401 Unauthorized) status
      at Context.<anonymous> (skr-test/test.js:42:13)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
```

Failing jobs:
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-preview-integration-dev
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-kyma-to-kyma2-upgrade-aws-dev
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-aws-svcat-migration-dev
- ... and more

**Comment by pbochynski** [comment]
Seems to be fixed now, but I will wait a little bit to see the pipeline results.
