### ISSUE TITLE
k3d pipelines fail to create k3d cluster

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#13700]
**Description**

There are many failures at the stage of creating k3d cluster:

```
Error: Executing 'k3d cluster create kyma --kubeconfig-update-default --timeout 300s --agents 1 --image rancher/k3s:v1.21.9-k3s1 --kubeconfig-switch-context --k3s-arg --disable=traefik@server:0 --registry-use kyma-registry:5001 --port 80:80@loadbalancer --port 443:443@loadbalancer' failed with output '[36mINFO[0m[0000] portmapping '80:80' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy] 
[36mINFO[0m[0000] portmapping '443:443' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy] 
[36mINFO[0m[0000] Prep: Network                                
[36mINFO[0m[0000] Created network 'k3d-kyma'                   
[36mINFO[0m[0000] Created volume 'k3d-kyma-images'             
[36mINFO[0m[0000] Starting new tools node...                   
[36mINFO[0m[0001] Creating node 'k3d-kyma-server-0'            
[36mINFO[0m[0001] Pulling image 'docker.io/rancher/k3d-tools:5.0.0' 
[36mINFO[0m[0002] Pulling image 'rancher/k3s:v1.21.9-k3s1'     
[36mINFO[0m[0003] Starting Node 'k3d-kyma-tools'               
[36mINFO[0m[0006] Creating node 'k3d-kyma-agent-0'             
[36mINFO[0m[0007] Creating LoadBalancer 'k3d-kyma-serverlb'    
[36mINFO[0m[0008] Pulling image 'docker.io/rancher/k3d-proxy:5.0.0' 
[36mINFO[0m[0011] Using the k3d-tools node to gather environment information 
[36mINFO[0m[0011] HostIP: using network gateway...             
[36mINFO[0m[0011] Starting cluster 'kyma'                      
[36mINFO[0m[0011] Starting servers...                          
[36mINFO[0m[0012] Deleted k3d-kyma-tools                       
[36mINFO[0m[0012] Starting Node 'k3d-kyma-server-0'            
[36mINFO[0m[0017] Starting agents...                           
[36mINFO[0m[0018] Starting Node 'k3d-kyma-agent-0'             
[36mINFO[0m[0030] Starting helpers...                          
[36mINFO[0m[0030] Starting Node 'k3d-kyma-serverlb'            
[36mINFO[0m[0037] Injecting record '172.18.0.1 host.k3d.internal'... 
[31mERRO[0m[0044] Failed Cluster Start: failed to patch CoreDNS with network members: failed to add host entry "172.18.0.4 k3d-kyma-agent-0" into CoreDNS: Failed to patch CoreDNS ConfigMap to include entry '172.18.0.4 k3d-kyma-agent-0' (see debug logs) 
[31mERRO[0m[0044] Failed to create cluster >>> Rolling Back    
[36mINFO[0m[0044] Deleting cluster 'kyma'                      
[36mINFO[0m[0045] Deleted k3d-kyma-serverlb                    
[36mINFO[0m[0045] Deleted k3d-kyma-server-0                    
[36mINFO[0m[0045] Deleted k3d-kyma-agent-0                     
[36mINFO[0m[0045] Deleting cluster network 'k3d-kyma'          
[36mINFO[0m[0046] Deleting image volume 'k3d-kyma-images'      
[31mFATA[0m[0046] Cluster creation FAILED, all changes have been rolled back! 
': exit status 1
```
Other error:
```
- Created k3d registry 'kyma-registry:5001'
client_loop: send disconnect: Broken pipe
ERROR: (gcloud.compute.ssh) [/usr/bin/ssh] exited with return code [255].
```

Affected jobs:
- https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d

Sample failures from last 2 days:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1506572851036033024/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1506542651439058944/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1506301056374542336/build-log.txt
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1506270857033420800/build-log.txt

**Expected result**

Pipelines are more stable.

**Comment by pbochynski** [comment]
Another error found in [kyma-integration-k3d-compass-dev](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev) job:
```
Error: Executing 'k3d cluster create kyma --kubeconfig-update-default --timeout 300s --agents 1 --image rancher/k3s:v1.21.9-k3s1 --kubeconfig-switch-context --k3s-arg --disable=traefik@server:0 --registry-use kyma-registry:5001 --port 80:80@loadbalancer --port 443:443@loadbalancer' failed with output '[36mINFO[0m[0000] portmapping '80:80' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy] 
[36mINFO[0m[0000] portmapping '443:443' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy] 
[36mINFO[0m[0000] Prep: Network                                
[36mINFO[0m[0000] Created network 'k3d-kyma'                   
[36mINFO[0m[0000] Created volume 'k3d-kyma-images'             
[36mINFO[0m[0000] Starting new tools node...                   
[36mINFO[0m[0001] Creating node 'k3d-kyma-server-0'            
[36mINFO[0m[0001] Pulling image 'docker.io/rancher/k3d-tools:5.0.0' 
[36mINFO[0m[0002] Pulling image 'rancher/k3s:v1.21.9-k3s1'     
[36mINFO[0m[0003] Starting Node 'k3d-kyma-tools'               
[36mINFO[0m[0006] Creating node 'k3d-kyma-agent-0'             
[36mINFO[0m[0007] Creating LoadBalancer 'k3d-kyma-serverlb'    
[36mINFO[0m[0008] Pulling image 'docker.io/rancher/k3d-proxy:5.0.0' 
[36mINFO[0m[0011] Using the k3d-tools node to gather environment information 
[36mINFO[0m[0011] HostIP: using network gateway...             
[36mINFO[0m[0011] Starting cluster 'kyma'                      
[36mINFO[0m[0011] Starting servers...                          
[36mINFO[0m[0012] Deleted k3d-kyma-tools                       
[36mINFO[0m[0012] Starting Node 'k3d-kyma-server-0'            
[36mINFO[0m[0017] Starting agents...                           
[36mINFO[0m[0018] Starting Node 'k3d-kyma-agent-0'             
[36mINFO[0m[0031] Starting helpers...                          
[36mINFO[0m[0031] Starting Node 'k3d-kyma-serverlb'            
[36mINFO[0m[0037] Injecting record '172.18.0.1 host.k3d.internal'... 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x28 pc=0x539946]

goroutine 1 [running]:
bufio.(*Reader).Read(0x0, {0xc000209600, 0xc000932000, 0xc0006969f8})
	/usr/local/go/src/bufio/bufio.go:206 +0x86
io.ReadAll({0xe62040, 0x0})
	/usr/local/go/src/io/io.go:633 +0xfe
io/ioutil.ReadAll(...)
	/usr/local/go/src/io/ioutil/ioutil.go:27
github.com/rancher/k3d/v5/pkg/client.corednsAddHost({0xe78c90, 0xc0001fd8c0}, {0xe98060, 0x148a8b8}, 0xc0004d08e0, {0xc0007e9db0, 0xc000129650}, {0xc00047bf68, 0x11})
	/drone/src/pkg/client/cluster.go:997 +0x347
github.com/rancher/k3d/v5/pkg/client.prepCoreDNSInjectNetworkMembers({0xe78c90, 0xc0001fd8c0}, {0xe98060, 0x148a8b8}, 0xc0004d08e0)
	/drone/src/pkg/client/cluster.go:1053 +0x2f9
github.com/rancher/k3d/v5/pkg/client.ClusterStart({0xe78c58, 0xc000034080}, {0xe98060, 0x148a8b8}, 0xc0004d08e0, {0x1, 0x45d964b800, {0xc00057a800, 0x2, 0x2}, ...})
	/drone/src/pkg/client/cluster.go:948 +0x120f
github.com/rancher/k3d/v5/pkg/client.ClusterRun({0xe78c58, 0xc000034080}, {0xe98060, 0x148a8b8}, 0xc0004d08c0)
	/drone/src/pkg/client/cluster.go:84 +0x32b
github.com/rancher/k3d/v5/cmd/cluster.NewCmdClusterCreate.func2(0xc000515400, {0xc0004e85a0, 0x1, 0x12})
	/drone/src/cmd/cluster/clusterCreate.go:174 +0x9cb
github.com/spf13/cobra.(*Command).execute(0xc000515400, {0xc0004e8480, 0x11, 0x12})
	/drone/src/vendor/github.com/spf13/cobra/command.go:860 +0x5f8
github.com/spf13/cobra.(*Command).ExecuteC(0xc000514c80)
	/drone/src/vendor/github.com/spf13/cobra/command.go:974 +0x3bc
github.com/spf13/cobra.(*Command).Execute(...)
	/drone/src/vendor/github.com/spf13/cobra/command.go:902
github.com/rancher/k3d/v5/cmd.Execute()
	/drone/src/cmd/root.go:147 +0x175
main.main()
	/drone/src/main.go:27 +0x17
': exit status 2
```
Log:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1506572851111530496/build-log.txt

**Comment by pbochynski** [comment]
We should use `kyma provision k3d` instead of bash command.

**Comment by lindnerby** [comment]
Actually both jobs are using Kyma CLI to provision k3d, the command itself creates the k3d output.
Although jobs are failing mostly due to tests not passing, the one particular error which has nothing to do with failing tests, but with patching core-dns during `k3d cluster create` has been fixed in k3d v5.0.1 (we are currently providing v5.0.0 in the vm image that runs some integration tests).
Prepared a PR to bump the version https://github.com/kyma-project/test-infra/pull/5163

**Comment by pbochynski** [comment]
Another problem:
- https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1508913287738167296

```
Error: Executing 'k3d cluster create kyma --kubeconfig-update-default --timeout 300s --agents 1 --image rancher/k3s:v1.21.9-k3s1 --kubeconfig-switch-context --k3s-arg --disable=traefik@server:0 --registry-use kyma-registry:5001 --port 80:80@loadbalancer --port 4[43](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1508913287738167296#1:build-log.txt%3A43):[44](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1508913287738167296#1:build-log.txt%3A44)3@loadbalancer --no-rollback' failed with output 'INFO[0000] portmapping '80:80' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy] 
INFO[0000] portmapping '443:443' targets the loadbalancer: defaulting to [servers:*:proxy agents:*:proxy] 
INFO[0000] Prep: Network                                
INFO[0000] Created network 'k3d-kyma'                   
INFO[0000] Created image volume k3d-kyma-images         
INFO[0000] Starting new tools node...                   
INFO[0001] Creating node 'k3d-kyma-server-0'            
INFO[0001] Pulling image 'docker.io/rancher/k3d-tools:5.3.0' 
INFO[0002] Pulling image 'rancher/k3s:v1.21.9-k3s1'     
INFO[0003] Starting Node 'k3d-kyma-tools'               
INFO[0007] Creating node 'k3d-kyma-agent-0'             
INFO[0007] Creating LoadBalancer 'k3d-kyma-serverlb'    
INFO[0008] Pulling image 'docker.io/rancher/k3d-proxy:5.3.0' 
INFO[0011] Using the k3d-tools node to gather environment information 
INFO[0011] HostIP: using network gateway 172.18.0.1 address 
INFO[0011] Starting cluster 'kyma'                      
INFO[0011] Starting servers...                          
INFO[0012] Starting Node 'k3d-kyma-server-0'            
ERRO[0014] Failed Cluster Start: Failed to start server k3d-kyma-server-0: Node k3d-kyma-server-0 failed to get ready: error waiting for log line `k3s is up and running` from node 'k3d-kyma-server-0': stopped returning log lines 
FATA[0014] Cluster creation FAILED, rollback deactivated. 
': exit status 1
```

**Comment by lindnerby** [comment]
Yes and also it seems that commercemock tests are failing more frequently with this version, need to test do more testing on a separate vm first. Will revert the version bump in the meantime: https://github.com/kyma-project/test-infra/pull/5199

**Comment by pbochynski** [comment]
Any progress here? @lindnerby do you need some help?

**Comment by lindnerby** [comment]
@pbochynski The current state is: 
I have done some testing on a GCP VM created with the same image as prow jobs use [kyma-deps-image-v20220401-e03c21](https://console.cloud.google.com/compute/imagesDetail/projects/sap-kyma-prow-workloads/global/images/kyma-deps-image-v20220401-e03c21?orgonly=true&project=sap-kyma-prow-workloads&supportedpurview=organizationId) to create a similar scenario to tests run on pipeline (same custom image with preinstalled dependencies).
Fast-integration tests can run after an upgrade of k3d to v5.4.1 (latest) 20+ times, and there are not problems whatsoever. Also the k3d cluster kyma can be deleted multiple times and provisioned again with Kyma CLI and then run tests again multiple times without problems.
But if tests are run via pjtester in a PR where the only change is the upgrade of k3d, there is a failure rate of ~80%.

Next step is to figure out what are the possible differences of the test setups, esp. what is the prow overhead that is failing the tests. I definitely need one from neighbours to support me and for finding one I am talking to @dekiel at the moment.

**Comment by pbochynski** [comment]
Thanks for update. Failures from today:
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1511963341306728448/build-log.txt 
- https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev/1511933142007549952/build-log.txt

```
[31mERRO[0m[0042] Failed Cluster Start: failed to patch CoreDNS with network members: failed to add host entry "172.18.0.3 k3d-kyma-server-0" into CoreDNS: Failed to patch CoreDNS ConfigMap to include entry '172.18.0.3 k3d-kyma-server-0' (see debug logs) 
[31mERRO[0m[0042] Failed to create cluster >>> Rolling Back    
```

**Comment by jakobmoellersap** [comment]
Since the CoreDNS patching occurs not only in kyma-integration-k3d-compass-dev but also other pipelines, I want to also of the other failures underlying the importance:
- nightly-main-reconciler-publish-unstable-cli  https://github.com/kyma-project/kyma/issues/13857 (https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-publish-unstable-cli/1510882532067905536#1:build-log.txt%3A431-432)

**Comment by lindnerby** [comment]
@jakobmoellersap The patched version got merged yesterday, let's observe jobs for today and see if we encounter job failures again caused by k3d:
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-integration-k3d-compass-dev
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-publish-unstable-cli

**Comment by lindnerby** [comment]
@pbochynski What was the frequency of cluster creation failures due to core-dns patch errors before? It seems that this particular issue is gone now.
