### ISSUE TITLE
Grafana CPU/memory charts not showing data as kube-state-metrics is panicing on bad ingress definition

### ISSUE THREAD

**Issue by a-thaler** [kyma-project/kyma#13768]
**Description**
Several charts in the dashboards being shipped with kyma 2.1.0 are not showing data. Especially the typical ones visualising CPU and memory usage.

These charts are based on aggregations with the kube_pod_info.

It turned out that in the affected cluster kube-state-metrics pods are in a constant crashloop. The related logs are showing a panic. A restart does not solve the situation.

The stacktrace of the panic is exactly the same as in https://github.com/kubernetes/kube-state-metrics/issues/1660. Indeed the cluster has some Ingresses defined.

```
k logs -n kyma-system monitoring-kube-state-metrics-5f99b4f9b7-lmsgv
I0328 14:47:06.573928       1 main.go:111] Using resources certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
I0328 14:47:06.573992       1 types.go:136] Using all namespace
I0328 14:47:06.573999       1 main.go:133] metric allow-denylisting: Excluding the following lists that were on denylist: 
W0328 14:47:06.574023       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0328 14:47:06.574538       1 main.go:247] Testing communication with server
I0328 14:47:06.685261       1 main.go:252] Running with Kubernetes cluster version: v1.21. git version: v1.21.9. git tree state: clean. commit: b631974d68ac5045e076c86a5c66fba6f128dc72. platform: linux/amd64
I0328 14:47:06.685284       1 main.go:254] Communication with server successful
I0328 14:47:06.685483       1 main.go:210] Starting metrics server: [::]:8080
I0328 14:47:06.685504       1 metrics_handler.go:96] Autosharding disabled
I0328 14:47:06.685553       1 main.go:199] Starting kube-state-metrics self metrics server: [::]:8081
I0328 14:47:06.685759       1 main.go:66] levelinfomsgTLS is disabled.http2false
I0328 14:47:06.685819       1 main.go:66] levelinfomsgTLS is disabled.http2false
W0328 14:47:06.771859       1 warnings.go:70] batch/v1beta1 CronJob is deprecated in v1.21+, unavailable in v1.25+; use batch/v1 CronJob
I0328 14:47:06.773208       1 builder.go:192] Active resources: certificatesigningrequests,configmaps,cronjobs,daemonsets,deployments,endpoints,horizontalpodautoscalers,ingresses,jobs,limitranges,mutatingwebhookconfigurations,namespaces,networkpolicies,nodes,persistentvolumeclaims,persistentvolumes,poddisruptionbudgets,pods,replicasets,replicationcontrollers,resourcequotas,secrets,services,statefulsets,storageclasses,validatingwebhookconfigurations,volumeattachments
E0328 14:47:06.871957       1 runtime.go:78] Observed a panic: "invalid memory address or nil pointer dereference" (runtime error: invalid memory address or nil pointer dereference)
goroutine 32 [running]:
k8s.io/apimachinery/pkg/util/runtime.logPanic({0x1631020, 0x2685d50})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:74 +0x7d
k8s.io/apimachinery/pkg/util/runtime.HandleCrash({0x0, 0x0, 0x2540be400})
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/runtime/runtime.go:48 +0x75
panic({0x1631020, 0x2685d50})
	/usr/local/go/src/runtime/panic.go:1038 +0x215
k8s.io/kube-state-metrics/v2/internal/store.ingressMetricFamilies.func6(0x70)
	/go/src/k8s.io/kube-state-metrics/internal/store/ingress.go:136 +0x189
k8s.io/kube-state-metrics/v2/internal/store.wrapIngressFunc.func1({0x17f9880, 0xc00048a170})
	/go/src/k8s.io/kube-state-metrics/internal/store/ingress.go:175 +0x49
k8s.io/kube-state-metrics/v2/pkg/metric_generator.(*FamilyGenerator).Generate(...)
	/go/src/k8s.io/kube-state-metrics/pkg/metric_generator/generator.go:67
k8s.io/kube-state-metrics/v2/pkg/metric_generator.ComposeMetricGenFuncs.func1({0x17f9880, 0xc00048a170})
	/go/src/k8s.io/kube-state-metrics/pkg/metric_generator/generator.go:107 +0xd8
k8s.io/kube-state-metrics/v2/pkg/metrics_store.(*MetricsStore).Add(0xc00068a740, {0x17f9880, 0xc00048a170})
	/go/src/k8s.io/kube-state-metrics/pkg/metrics_store/metrics_store.go:72 +0xd4
k8s.io/kube-state-metrics/v2/pkg/metrics_store.(*MetricsStore).Replace(0xc00068a740, {0xc000556190, 0x5, 0x1443e01}, {0xc0000a1be0, 0xc088907ab3f6a5cc})
	/go/src/k8s.io/kube-state-metrics/pkg/metrics_store/metrics_store.go:134 +0xa5
k8s.io/client-go/tools/cache.(*Reflector).syncWith(0xc000542620, {0xc000556140, 0x5, 0x0}, {0xc0000240d8, 0x7})
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:456 +0x98
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch.func1(0xc000542620, 0xc000022a20, 0xc00052e2a0, 0xc0000a1d60)
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:354 +0x7ab
k8s.io/client-go/tools/cache.(*Reflector).ListAndWatch(0xc000542620, 0xc00052e2a0)
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:361 +0x265
k8s.io/client-go/tools/cache.(*Reflector).Run.func1()
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:221 +0x26
k8s.io/apimachinery/pkg/util/wait.BackoffUntil.func1(0x7fdbdf1e52a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:155 +0x67
k8s.io/apimachinery/pkg/util/wait.BackoffUntil(0xc00019cd00, {0x1a0dd20, 0xc000556000}, 0x1, 0xc00052e2a0)
	/go/pkg/mod/k8s.io/apimachinery@v0.23.0/pkg/util/wait/wait.go:156 +0xb6
k8s.io/client-go/tools/cache.(*Reflector).Run(0xc000542620, 0xc00052e2a0)
	/go/pkg/mod/k8s.io/client-go@v0.23.0/tools/cache/reflector.go:220 +0x1f8
created by k8s.io/kube-state-metrics/v2/internal/store.(*Builder).startReflector
	/go/src/k8s.io/kube-state-metrics/internal/store/builder.go:427 +0x2c8
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x20 pc=0x14844a9]
```

**Expected result**

**Actual result**

**Steps to reproduce**

**Troubleshooting**
Removing the ingress resource from the kube-state-metrics configuration in the deployment solved the problem.

**Comment by chrkl** [comment]
Solved by deactivating ingress metrics in kube-state-metrics.
