### ISSUE TITLE
Flaky test case : "Getting Started Guide Tests"  

### ISSUE THREAD

**Issue by kwiatekus** [kyma-project/kyma#13872]
**Description**

kyma-integration-k3d test sometimes fails with 

```
  1) Executing Standard Testsuite:
       Getting Started Guide Tests:
         Order should be persisted and should survive pod restarts (redis storage):
     Error: Order not found: 762727210
      at findOrder (test/fixtures/getting-started-guide/index.js:98:9)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async verifyOrderPersisted (test/fixtures/getting-started-guide/index.js:84:3)
      at async Context.<anonymous> (test/2-getting-started-guide.js:36:7)
```
I.e [here](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-integration-k3d/1511842544034516992/build-log.txt) 

**Troubleshooting**

Let's make sure that the redis storage instance is properly bound to the function. ( i.e via additional assertion )
The symptoms show that the order is not found after function pod restart.
This could be the because of problems with service binding - therefore after  function pod restarts the inmemory storage is lost.
We had been experiencing issues with service bindings to function pods here as well
https://github.com/kyma-project/kyma/issues/13443

**Comment by kwiatekus** [comment]
Some of the failing tests can be found [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1521/pre-main-control-plane-reconciler-e2e/1511687021553258496/build-log.txt), [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1477/pre-main-control-plane-reconciler-e2e/1509153873531506688/build-log.txt
), [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1477/pre-main-control-plane-reconciler-e2e/1508791476417466368/build-log.txt) and [here](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/1467/pre-main-control-plane-reconciler-e2e/1504732331099820032/build-log.txt).
