### ISSUE TITLE
Pipeline `skr-aws-upgrade-integration-dev` fails during interaction with Compass

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#14386]
**Description**

The pipelines`skr-aws-upgrade-integration-dev` fails with a Compass issue:

```
1) SKR-Upgrade-test
       Assign SKR to scenario:
     Error: Error when updating label definition with key scenarios: Error: Error calling Director API: 422 Unprocessable Entity
      at DirectorClient.updateLabelDefinition (compass/client.js:176:13)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async addScenarioInCompass (compass/helpers.js:21:3)
      at async Context.<anonymous> (skr-aws-upgrade-integration/index.js:166:5)

```

Response from Compasss is: `422 Unprocessable Entity`.

See [logs](https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-upgrade-integration-dev/1529311374713294848/build-log.txt):

**Expected result**

Pipelines is passing successfully.

**Actual result**

Pipelines files with issue during Compass interaction.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
Related to https://github.com/kyma-project/kyma/issues/14368
