### ISSUE TITLE
skr-aws-integration-dev provisioning failed: Error calling Director API: 422 Unprocessable Entity

### ISSUE THREAD

**Issue by tillknuesting** [kyma-project/kyma#14495]
https://storage.googleapis.com/kyma-prow-logs/logs/skr-aws-integration-dev/1533615976401080320/build-log.txt

```
     "before all" hook: Ensure SKR is provisioned for "Execute the tests":
     Error: Provisioning failed: Error: Error when updating label definition with key scenarios: Error: Error calling Director API: 422 Unprocessable Entity
      at provisionSKRInstance (skr-test/provision/provision-skr.js:37:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-test/test.js:53:15)
```

**Comment by tillknuesting** [comment]
```
 1) SKR test
       "before all" hook: Ensure SKR is provisioned for "Execute the tests":
     Error: Provisioning failed: Error: Error when updating label definition with key scenarios: Error: Error calling Director API: 422 Unprocessable Entity
      at provisionSKRInstance (skr-test/provision/provision-skr.js:37:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-test/test.js:53:15)
```
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-aws-integration-dev/1534340920911073280
