### ISSUE TITLE
skr-aws-integration-dev pipeline fails: Director API: 500 Internal Server Error

### ISSUE THREAD

**Issue by tillknuesting** [kyma-project/kyma#14567]
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/skr-aws-integration-dev/1536152810297495552

```
  1) SKR test
       "before all" hook: Ensure SKR is provisioned for "Execute the tests":
     Error: Provisioning failed: Error: Error when updating label definition with key scenarios: Error: Error calling Director API: 500 Internal Server Error
      at provisionSKRInstance (skr-test/provision/provision-skr.js:34:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (skr-test/test.js:53:15)
```

**Comment by Sawthis** [comment]
Periodic [skr-aws-integration-dev](https://status.build.kyma-project.io/?type=periodic&job=skr-aws-integration-dev) job failed 2 times in last 24h counting from 15.06.2022 11AM.

**Comment by tillknuesting** [comment]
resolved
