### ISSUE TITLE
Integration tests fails consistently after upgrade in `kyma-upgrade-gardener-kyma2-to-main`

### ISSUE THREAD

**Issue by tobiscr** [kyma-project/kyma#14649]
**Description**

The CI/CD pipeline [`kyma-upgrade-gardener-kyma2-to-main`](https://status.build.kyma-project.io/?job=kyma-upgrade-gardener-kyma2-to-main-reconciler-main) fails consistently after since several days after upgrading from Kyma `2.3.0` to `main` and running the fast-integration tests.

Failing test case is:

```
  Upgrade test preparation
[ERROR] HttpError: HTTP request failed
    1) CommerceMock test fixture should be ready


  0 passing (3s)
  1 failing

  1) Upgrade test preparation
       CommerceMock test fixture should be ready:
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

Example: 
* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1539518671766949888/build-log.txt
* https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1537827523306459136/build-log.txt

**Expected result**

Fast integartion tests are passed successfully after upgrading from Kyma `2.3.0` to `main`.

**Actual result**

Fast integration test fails consistently.

**Steps to reproduce**

**Troubleshooting**

**Comment by tobiscr** [comment]
Duplicate of https://github.com/kyma-project/kyma/issues/14587
