### ISSUE TITLE
KEB Provisioning failure due to certificate issue 

### ISSUE THREAD

**Issue by raypinto** [kyma-project/kyma#14651]
**Description**

The [skr-eventing](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-skr-eventing) pipeline fails during the provisioning step with the following error:

```
Error: unable to verify the first certificate
      at TLSSocket.onConnectSecure (_tls_wrap.js:1515:34)
      at TLSSocket._finishInit (_tls_wrap.js:937:8)
      at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:709:12)
```

**Expected result**

The provisioning succeeds and the pipeline is green

**Actual result**

The provisioning fails and the pipeline is red

**Comment by raypinto** [comment]
Closing this issue as the problem is being tracked [here](https://github.com/kyma-project/kyma/issues/14650).
