### ISSUE TITLE
Failing kyma-upgrade-k3d-kyma2-to-main with Error: cannot get jaeger trace

### ISSUE THREAD

**Issue by adityabhatia** [kyma-project/kyma#14697]
**Description**

Failing [kyma-upgrade-k3d-kyma2-to-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main) with Error: cannot get jaeger trace
```
  1) Upgrade test tests
       Tracing Tests:
         with Nats backend
           in-cluster structured event should have correct tracing spans:
     Error: cannot get jaeger trace
404: Not Found: {"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":404,"msg":"trace not found"}]}
      at convertAxiosError (utils/index.js:116:10)
      at getJaegerTrace (tracing/client.js:23:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkTrace (test/fixtures/commerce-mock/index.js:323:20)
      at async checkInClusterEventTracing (test/fixtures/commerce-mock/index.js:319:3)
      at async Context.<anonymous> (tracing/index.js:30:9)
```

**Comment by adityabhatia** [comment]
Other pipelines are failing as well https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main

**Comment by varbanv** [comment]
@k15r could you take a look at this, it seems to be affecting a number of tests and looks like it could be related to the NATS Jetstream changes?

**Comment by raypinto** [comment]
@varbanv we are looking into it. Will update the issue with our finding ASAP!

**Comment by raypinto** [comment]
So @rakesh-garimella and me tried to debug the issue. The issue is that the trace id of an event sent to the function is not found in jaeger. When the function was restarted, the trace id was then found on jaeger.

The issue could be that the envoy proxies were not updated with the latest config and we need to restart them after upgrade. We need to further check this issue with goats.

**Comment by pPrecel** [comment]
Do you have an example trace? If the problem is with the function then their trace should exist but it would end on istio proxy (istio sidecar is sending spans as well)

Where can I find the test scenario?

**Comment by raypinto** [comment]
After upgrading kyma from 2.3.0 to main: The trace id obtained from the response header after sending an event, does not exist on jaeger. You could reproduce the issue by:
- Install kyma 2.3.0 
- Run [eventing test-prep](https://github.com/kyma-project/kyma/blob/049627b1b2e30986ea54def72d854c2e71242207/tests/fast-integration/package.json#L28)
- Run the fast-integration [eventing test](https://github.com/kyma-project/kyma/blob/049627b1b2e30986ea54def72d854c2e71242207/tests/fast-integration/package.json#L29). Everything should work fine (including the [tracing test](https://github.com/kyma-project/kyma/blob/049627b1b2e30986ea54def72d854c2e71242207/tests/fast-integration/test/fixtures/commerce-mock/index.js#L322))
- Upgrade kyma to main
- Again run the [eventing tests](https://github.com/kyma-project/kyma/blob/049627b1b2e30986ea54def72d854c2e71242207/tests/fast-integration/package.json#L29).
- The tracing test fails with an error saying that the trace cannot be found
- Kick the function (lastorder) pod
- Run the test again. The test works fine and the tracing id is now visible in jaeger.

**Comment by pPrecel** [comment]
Thanks. I'm going to reproduce it

**Comment by raypinto** [comment]
Just FYI: The upgrade test does not fail now, since we have a new kyma version released. So the pipeline currently tests upgrade from 2.4.2 to main.

**Comment by khlifi411** [comment]
Update: now this pipeline [kyma-upgrade-gardener-kyma2-minor-versions](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions) is failing with this error.

**Comment by varbanv** [comment]
It looks like the pipeline is green now.
