### ISSUE TITLE
Failing pipeline skr-aws-upgrade-integration-dev

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#14738]
**Description**

Job is failing since June 20: 100% failure rate
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/skr-aws-upgrade-integration-dev

**Expected result**

SKR cluster provisioning succeeds

**Actual result**

Pipeline failing during provisioning of SKR cluster:

```
4 passing (2h)
  18 failing

  1) SKR-Upgrade-test
       Provision SKR with ID 068ccc6e-9fd7-4b39-bdbf-e73bd268d856:
     Error: Error: wait timeout
Error thrown by ensureOperationSucceeded: Runtime status: {
	"data": [
		{
			"instanceID": "068ccc6e-9fd7-4b39-bdbf-e73bd268d856",
			"runtimeID": "80295dea-b965-495f-9d1d-cb5f5e322812",
			"globalAccountID": "e449f875-b5b2-4485-b7c0-98725c0571bf",
			"subscriptionGlobalAccountID": "",
			"subAccountID": "prow-keb-integration",
			"region": "eu-central-1",
			"subAccountRegion": "cf-eu10",
			"shootName": "e74a416",
			"serviceClassID": "47c9dcbf-ff30-448e-ab36-d3bad66ba281",
			"serviceClassName": "kymaruntime",
			"servicePlanID": "361c511f-f939-4621-b228-d0fb79a1fe15",
			"servicePlanName": "aws",
			"provider": "AWS",
			"status": {
				"createdAt": "2022-07-04T00:00:54.489118Z",
				"modifiedAt": "2022-07-04T00:08:56.410799Z",
				"state": "provisioning",
				"provisioning": {
					"state": "in progress",
					"description": "Operation created",
					"createdAt": "2022-07-04T00:00:54.483448Z",
					"operationID": "0ec9d6bb-2663-4002-9436-4502fc7d61ca"
				}
			},
			"userID": "test@test.com",
			"avsInternalEvaluationID": 208983360,
			"kymaVersion": "2.3.0"
		}
	],
	"count": 1,
	"totalCount": 1
}
      at /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/kyma-environment-broker/helpers.js:104:11
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async ensureOperationSucceeded (kyma-environment-broker/helpers.js:97:15)
      at async provisionSKR (kyma-environment-broker/helpers.js:29:3)
      at async Context.<anonymous> (skr-aws-upgrade-integration/index.js:131:11)
```

**Related issue**
[Periodic: skr-aws-upgrade-integration-dev ](https://github.com/kyma-project/test-infra/issues/5523)

**Comment by tobiscr** [comment]
@khlifi411 : is this issue still valid? I mean we have this issue no longer- maybe we can close this ticket?

**Comment by khlifi411** [comment]
Closing as error is not happening anymore
