### ISSUE TITLE
Job `kyma-upgrade-gardener-kyma2-minor-versions` is failing with many errors

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#14757]
**Description**

Job [kyma-upgrade-gardener-kyma2-minor-versions](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions) is failing with many errors related to `logging`, `monitoring` and `tracing`.

**Expected result**

Job `kyma-upgrade-gardener-kyma2-minor-versions` should succeed

**Actual result**

```
9 passing (7m)
  9 failing

  1) Upgrade test tests
       Grafana Tests:
         Grafana redirects should work:
     Error: Waiting for deployment monitoring-auth-proxy-grafana timeout (90000 ms)
      at Timeout._onTimeout (utils/index.js:337:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

  2) Upgrade test tests
       Prometheus Tests:
         Prometheus targets should be healthy:
     Error: cannot get prometheus targets: TypeError: Cannot read property 'activeTargets' of undefined
      at convertAxiosError (utils/index.js:104:12)
      at getPrometheusActiveTargets (monitoring/client.js:52:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/monitoring/prometheus.js:30:27
      at async retry (monitoring/prometheus.js:317:12)
      at async Object.assertAllTargetsAreHealthy (monitoring/prometheus.js:29:28)
      at async Context.<anonymous> (monitoring/index.js:36:7)

  3) Upgrade test tests
       Prometheus Tests:
         No critical Prometheus alerts should be firing:
     Error: cannot get prometheus alerts: TypeError: Cannot read property 'alerts' of undefined
      at convertAxiosError (utils/index.js:104:12)
      at getPrometheusAlerts (monitoring/client.js:62:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/monitoring/prometheus.js:44:23
      at async retry (monitoring/prometheus.js:317:12)
      at async Object.assertNoCriticalAlertsExist (monitoring/prometheus.js:43:24)
      at async Context.<anonymous> (monitoring/index.js:40:7)

  4) Upgrade test tests
       Prometheus Tests:
         Prometheus scrape pools should have a target:
     Error: cannot get prometheus targets: TypeError: Cannot read property 'activeTargets' of undefined
      at convertAxiosError (utils/index.js:104:12)
      at getPrometheusActiveTargets (monitoring/client.js:52:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/monitoring/prometheus.js:58:27
      at async retry (monitoring/prometheus.js:317:12)
      at async Object.assertScrapePoolTargetsExist (monitoring/prometheus.js:56:28)
      at async Context.<anonymous> (monitoring/index.js:44:7)

  5) Upgrade test tests
       Prometheus Tests:
         Prometheus rules should be registered:
     Error: cannot get prometheus rules: TypeError: Cannot read property 'groups' of undefined
      at convertAxiosError (utils/index.js:104:12)
      at getPrometheusRuleGroups (monitoring/client.js:72:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async getRegisteredPrometheusRuleNames (monitoring/prometheus.js:290:17)
      at async getNotRegisteredPrometheusRuleNames (monitoring/prometheus.js:306:27)
      at async retry (monitoring/prometheus.js:317:12)
      at async Object.assertRulesAreRegistered (monitoring/prometheus.js:151:30)
      at async Context.<anonymous> (monitoring/index.js:48:7)

  6) Upgrade test tests
       Prometheus Tests:
         Prometheus rules should be healthy:
     Error: cannot get prometheus rules: TypeError: Cannot read property 'groups' of undefined
      at convertAxiosError (utils/index.js:104:12)
      at getPrometheusRuleGroups (monitoring/client.js:72:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/monitoring/prometheus.js:73:24
      at async retry (monitoring/prometheus.js:317:12)
      at async Object.assertAllRulesAreHealthy (monitoring/prometheus.js:72:26)
      at async Context.<anonymous> (monitoring/index.js:52:7)

  7) Upgrade test tests
       Prometheus Tests:
         Metrics used by Kyma Dashboard should exist:
     Error: cannot query prometheus: TypeError: Cannot read property 'result' of undefined
      at convertAxiosError (utils/index.js:104:12)
      at queryPrometheus (monitoring/client.js:82:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async assertTimeSeriesExist (monitoring/prometheus.js:270:16)
      at async Object.assertMetricsExist (monitoring/prometheus.js:141:9)
      at async Context.<anonymous> (monitoring/index.js:56:7)

  8) Upgrade test tests
       Logging Tests:
         Check Loki logs from kyma-system namespace:
     TypeError: Cannot read property 'result' of undefined
      at logsPresentInLoki (logging/client.js:30:27)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Object.checkKymaLogs (logging/loki.js:21:33)
      at async Context.<anonymous> (logging/index.js:10:7)

  9) Upgrade test tests
       Tracing Tests:
         with Nats backend
           in-cluster structured event should have correct tracing spans:
     AssertionError: Target cannot be null or undefined.
      at checkTrace (test/fixtures/commerce-mock/index.js:326:33)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkInClusterEventTracing (test/fixtures/commerce-mock/index.js:319:3)
      at async Context.<anonymous> (tracing/index.js:30:9)

```

**Comment by a-thaler** [comment]
Seemed to happen only once. First test failure indicates already that a deployment was not even coming up. We should introduce a more general health check running before any test execution which checks all deployments for healthiness and prints typical diagnostic informations if not...

**Comment by a-thaler** [comment]
@pPrecel is there maybe a workaround available which we can apply to the job after the upgrade phase so that the problem gets silenced for now? Maybe restarting all functions?

**Comment by a-thaler** [comment]
I added a workaround by restarting all functions after upgrade which looks promising.
Also I increased the minNodes for azure (was done already for other providers) to avoid timeouts on first installation

**Comment by a-thaler** [comment]
The mentioned problem did not occur anymore, the "trace cannot be found" problem disappeared by having the workaround, timeouts on first installation are less, however we have random failures which are very close to the ones observed in the other pipeline: https://github.com/kyma-project/kyma/issues/14587
I will close this ticket here and will add the job to the other ticket as well
