### ISSUE TITLE
Failing pipeline kyma-upgrade-k3d-kyma2-to-main

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/kyma#14870]
**Description**
In recent failing job, the upgrade test failed with Nats backend
https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main

**Expected result**

**Actual result**

```
   17 passing (4m)
  1 failing
  1) Upgrade test tests
       Tracing Tests:
         with Nats backend
           Wait until subscriptions are ready:
     Error: Waiting for order-created subscription timeout (180000 ms)
      at Timeout._onTimeout (utils/index.js:337:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

Jul 21 10:00:57 https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1550027991336095744
Jul 20 12:00:40 https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1549695735413346304

```
   15 passing (4m)
  3 failing
  1) Upgrade test tests
       in-cluster event should be delivered (legacy events, structured and binary cloud events):
     Error: Fetching published event responded with error: AssertionError: The same event id expected in the result: expected { Object (podName) } to have nested property 'event.id'
      at convertAxiosError (utils/index.js:104:12)
      at /home/sa_117798148653314453801/kyma/tests/fast-integration/test/fixtures/commerce-mock/index.js:793:15
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async ensureInClusterEventReceivedWithRetry (test/fixtures/commerce-mock/index.js:777:10)
      at async checkInClusterEventDelivery (test/fixtures/commerce-mock/index.js:714:3)
      at async Context.<anonymous> (upgrade-test/upgrade-test-tests.js:27:5)
  2) Upgrade test tests
       Tracing Tests:
         with Nats backend
           Wait until subscriptions are ready:
     Error: Waiting for order-received subscription timeout (180000 ms)
      at Timeout._onTimeout (utils/index.js:337:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
  3) Upgrade test tests
       Tracing Tests:
         with Nats backend
           in-cluster structured event should have correct tracing spans:
     Error: Fetching published event responded with error: AssertionError: The same event id expected in the result: expected { Object (podName) } to have nested property 'event.id'
      at convertAxiosError (utils/index.js:104:12) 
```
Jul 22 08:00:13 https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1550360003116797952

**Steps to reproduce**

**Troubleshooting**

**Comment by jakobmoellersap** [comment]
New Error is related to Upgrade Tests:

```
in-cluster event should be delivered (legacy events, structured and binary cloud events):
     Error: Fetching published event responded with error: AssertionError: The same event id expected in the result: expected { Object (podName) } to have nested property 'event.id'
      at convertAxiosError (utils/index.js:104:12)
```

**Comment by tobiscr** [comment]
Pipeline back to normal: https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main 

Closing this issue
