### ISSUE TITLE
`pre-main-kyma-gardener-gcp-eventing-upgrade` is flaky

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#15723]
[pre-main-kyma-gardener-gcp-eventing-upgrade](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-gardener-gcp-eventing-upgrade) is flaky and regularly fails with:

```
1) Eventing tests
       with Nats backend
         In-cluster event should have correct tracing spans:
     Error: cannot get jaeger trace
404: Not Found: {"data":null,"total":0,"limit":0,"offset":0,"errors":[{"code":404,"msg":"trace not found"}]}
      at convertAxiosError (utils/index.js:116:10)
      at getJaegerTrace (tracing/client.js:23:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkTrace (test/fixtures/commerce-mock/index.js:323:20)
      at async checkInClusterEventTracing (test/fixtures/commerce-mock/index.js:319:3)
      at async Context.<anonymous> (eventing-test/eventing-test.js:200:7)
```

**Comment by friedrichwilken** [comment]
we found that there is an issue with the lastorder `function` due to changes in kyma internals during the upgrade. This can be resolved by rebuilding the function after the upgrade.

**Comment by friedrichwilken** [comment]
This PR is going to resolve this issue: https://github.com/kyma-project/kyma/pull/15792

**Comment by friedrichwilken** [comment]
This PR will rise the test's reliability further: #15769
