### ISSUE TITLE
Failing tracing test in pre-main-control-plane pipeline

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#15763]
**Description**

The [pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener) pipeline is failing at the following test:

```log
 19 passing (1m)
  1 failing

  1) Upgrade test tests
       Tracing Tests:
         with Nats backend
           in-cluster structured event should have correct tracing spans:

      AssertionError: expected 4 to be at least 5      
      actual expected
      
      45
      
      at checkTrace (test/fixtures/commerce-mock/index.js:330:43)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkInClusterEventTracing (test/fixtures/commerce-mock/index.js:319:3)
      at async Context.<anonymous> (tracing/index.js:30:9)
```

**Expected result**

Tracing Tests should succeed

**Comment by raypinto** [comment]
The job looks to be fine. The last three failures are not related to tracing and hence closing it
