### ISSUE TITLE
Observability components unavailable after upgrade

### ISSUE THREAD

**Issue by clebs** [kyma-project/kyma#15845]
**Description**
The observability components are not working after a minor version upgrade on https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-minor-versions.

Error log:
```
1) Upgrade test tests
       Grafana Tests:
         Grafana redirects should work:
     Error: Waiting for deployment monitoring-auth-proxy-grafana timeout (90000 ms)
      at Timeout._onTimeout (utils/index.js:342:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
  2) Upgrade test tests
       Prometheus Tests:
         Prometheus targets should be healthy:
     Error: cannot get prometheus targets
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:116:10)
      at getPrometheusActiveTargets (monitoring/client.js:57:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/monitoring/prometheus.js:51:27
      at async retry (monitoring/prometheus.js:336:12)
      at async Object.assertAllTargetsAreHealthy (monitoring/prometheus.js:50:28)
      at async Context.<anonymous> (monitoring/index.js:40:7)
  3) Upgrade test tests
       Prometheus Tests:
         No critical Prometheus alerts should be firing:
     Error: cannot get prometheus alerts
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:116:10)
      at getPrometheusAlerts (monitoring/client.js:67:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/monitoring/prometheus.js:38:23
      at async retry (monitoring/prometheus.js:336:12)
      at async Object.assertNoCriticalAlertsExist (monitoring/prometheus.js:37:24)
      at async Context.<anonymous> (monitoring/index.js:44:7)
  4) Upgrade test tests
       Prometheus Tests:
         Prometheus scrape pools should have a target:
     Error: cannot get prometheus targets
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:116:10)
      at getPrometheusActiveTargets (monitoring/client.js:57:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/monitoring/prometheus.js:66:27
      at async retry (monitoring/prometheus.js:336:12)
      at async Object.assertScrapePoolTargetsExist (monitoring/prometheus.js:64:28)
      at async Context.<anonymous> (monitoring/index.js:48:7)
  5) Upgrade test tests
       Prometheus Tests:
         Prometheus rules should be registered:
     Error: cannot get prometheus rules
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:116:10)
      at getPrometheusRuleGroups (monitoring/client.js:77:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async getRegisteredPrometheusRuleNames (monitoring/prometheus.js:309:17)
      at async getNotRegisteredPrometheusRuleNames (monitoring/prometheus.js:325:27)
      at async retry (monitoring/prometheus.js:336:12)
      at async Object.assertRulesAreRegistered (monitoring/prometheus.js:170:30)
      at async Context.<anonymous> (monitoring/index.js:52:7)
  6) Upgrade test tests
       Prometheus Tests:
         Prometheus rules should be healthy:
     Error: cannot get prometheus rules
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:116:10)
      at getPrometheusRuleGroups (monitoring/client.js:77:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async /home/prow/go/src/github.com/kyma-project/kyma/tests/fast-integration/monitoring/prometheus.js:81:24
      at async retry (monitoring/prometheus.js:336:12)
      at async Object.assertAllRulesAreHealthy (monitoring/prometheus.js:80:26)
      at async Context.<anonymous> (monitoring/index.js:56:7)
  7) Upgrade test tests
       Prometheus Tests:
         Metrics used by Kyma Dashboard should exist:
     Error: cannot query prometheus
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:116:10)
      at queryPrometheus (monitoring/client.js:87:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async assertTimeSeriesExist (monitoring/prometheus.js:289:16)
      at async Object.assertMetricsExist (monitoring/prometheus.js:160:9)
      at async Context.<anonymous> (monitoring/index.js:60:7)
  8) Upgrade test tests
       Logging Tests:
         Check Loki logs from kyma-system namespace:
     Error: cannot query loki
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:116:10)
      at queryLoki (logging/client.js:46:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async logsPresentInLoki (logging/client.js:18:26)
      at async Object.checkKymaLogs (logging/loki.js:30:33)
      at async Context.<anonymous> (logging/index.js:21:7)
  9) Upgrade test tests
       Logging Tests:
         Istio Access Logs tests
           Should create the Istio Access Logs resource for Loki:
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
  10) Upgrade test tests
       Logging Tests:
         Istio Access Logs tests
           Should query Loki and verify format of Istio Access Logs:
     Error: cannot query loki
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:116:10)
      at queryLoki (logging/client.js:46:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Object.verifyIstioAccessLogFormat (logging/loki.js:63:24)
      at async Context.<anonymous> (logging/index.js:51:7)
  11) Upgrade test tests
       Tracing Tests:
         with Nats backend
           in-cluster structured event should have correct tracing spans:
     Error: cannot get jaeger trace
503: Service Unavailable: "no healthy upstream"
      at convertAxiosError (utils/index.js:116:10)
      at getJaegerTrace (tracing/client.js:23:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkTrace (test/fixtures/commerce-mock/index.js:323:20)
      at async checkInClusterEventTracing (test/fixtures/commerce-mock/index.js:319:3)
      at async Context.<anonymous> (tracing/index.js:30:9)
```

**Expected result**

Job succeeds.

**Actual result**

Prow job is failing.

**Steps to reproduce**

Run the minor version upgrade job.

**Comment by a-thaler** [comment]
The pipeline tries to upgrade from 2.6.3 to 2.7.2.
The tests are failing after kyma 2.6.3 got installed, before the actual upgrade.

**Comment by a-thaler** [comment]
I tried to reproduce it and was not successful. As all test cases are indicating a 503 respond I assume that the istio virtualservices were not ready yet.
There were three job runs failing in a row but only one of them showed this results here. Still, the third run also revealed a 503 problem. 
So for sure it is not boiling down to an actual problem but a test flakyness. I have currently no idea on how to improve that

**Comment by a-thaler** [comment]
Newest run was green, will close the issue ..
