### ISSUE TITLE
improve logging of traces/spans in the upgrade tests

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#16007]
The upgrade test keeps breaking at the spans check. To find out what is going on, one must run the test locally to be able to debug it and to be able to compare the actual with the expected values.
Let's improve this situation by logging both - the graphs of the expected and the actual spans. 

Because this doesn't really help:
```
  1) Eventing tests
       with Nats backend
         In-cluster event should have correct tracing spans:
      AssertionError: expected false to be true      
      actual expected
      
      falsetrue
      
      at checkTrace (test/fixtures/commerce-mock/index.js:344:25)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkInClusterEventTracing (test/fixtures/commerce-mock/index.js:319:3)
      at async Context.<anonymous> (eventing-test/eventing-test.js:208:7)
```

**Comment by friedrichwilken** [comment]
https://github.com/kyma-project/kyma/pull/16094
