### ISSUE TITLE
Eventing unit/integration tests are flaky

### ISSUE THREAD

**Issue by mfaizanse** [kyma-project/kyma#16331]
The eventing unit and integration tests are too flaky, especially on local machine.

The most flaky tests are:
- `FAIL: TestJSSubscriptionWithDuplicateFilters (0.13s)`
- `FAIL: TestJSSubscriptionWithMaxInFlightChange (0.13s)`
- `Should recreate BEB Subscription again [It]`
        - `/home/prow/go/src/github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/beb/reconciler_integration_test.go:1000`

**Prow jobs:**
   - https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/16264/pull-eventing-controller-unit-test/1601230832385658880
   - https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/16308/pull-eventing-controller-unit-test/1601230451882594304

**On local machine:**
1. In eventing dir: `cd components/eventing-controller`
2. Run: `make test-local`

Also, on local machine, its leaving behind dangling `api-server` and `etcd` instances.

**Comment by mfaizanse** [comment]
Logs from local machine on `make test-local`:
```
--- FAIL: TestCreateSubscription (139.88s)
    --- FAIL: TestCreateSubscription/create_and_delete (10.04s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.000s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c1560>: {
                    Fields: {
                        "Status": <*matchers.EqualMatcher | 0xc000f167b0>{
                            Expected: <v1.ConditionStatus>"True",
                        },
                        "Type": <*matchers.EqualMatcher | 0xc000f16760>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16780>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f16790>{Expected: <string>""},
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/filter_with_empty_event_type (10.03s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.000s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c16b0>: {
                    Fields: {
                        "Type": <*matchers.EqualMatcher | 0xc000f16810>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16830>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription not active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f16850>{
                            Expected: <string>"failed to get clean subjects: nats: invalid subject",
                        },
                        "Status": <*matchers.EqualMatcher | 0xc000f16870>{
                            Expected: <v1.ConditionStatus>"False",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/invalid_sink;_misses_'http'_and_'https' (10.06s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.001s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c1770>: {
                    Fields: {
                        "Status": <*matchers.EqualMatcher | 0xc000f168f0>{
                            Expected: <v1.ConditionStatus>"False",
                        },
                        "Type": <*matchers.EqualMatcher | 0xc000f16890>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f168b0>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription not active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f168d0>{
                            Expected: <string>"subscription sink URL scheme should be 'http' or 'https'",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/invalid_sink;_invalid_character (10.03s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.000s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c1830>: {
                    Fields: {
                        "Type": <*matchers.EqualMatcher | 0xc000f16910>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16930>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription not active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f16950>{
                            Expected: <string>"failed to parse subscription sink URL: parse \"http://127.0.0. 1\": invalid character \" \" in host name",
                        },
                        "Status": <*matchers.EqualMatcher | 0xc000f16970>{
                            Expected: <v1.ConditionStatus>"False",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/invalid_sink;_missing_suffix_'svc.cluster.local' (10.03s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.001s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c18f0>: {
                    Fields: {
                        "Type": <*matchers.EqualMatcher | 0xc000f16990>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f169b0>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription not active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f169d0>{
                            Expected: <string>"failed to validate subscription sink URL. It does not contain suffix: svc.cluster.local",
                        },
                        "Status": <*matchers.EqualMatcher | 0xc000f169f0>{
                            Expected: <v1.ConditionStatus>"False",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/invalid_sink;_too_many_sub_domains (10.03s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.000s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c19b0>: {
                    Fields: {
                        "Type": <*matchers.EqualMatcher | 0xc000f16a10>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16a30>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription not active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f16a50>{
                            Expected: <string>"failed to validate subscription sink URL. It should contain 5 sub-domains: testapp.testsub.test.svc.cluster.local",
                        },
                        "Status": <*matchers.EqualMatcher | 0xc000f16a70>{
                            Expected: <v1.ConditionStatus>"False",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/invalid_sink;_wrong_namespace (10.05s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.001s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c1a70>: {
                    Fields: {
                        "Type": <*matchers.EqualMatcher | 0xc000f16a90>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16ab0>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription not active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f16ad0>{
                            Expected: <string>"namespace of subscription: test and the namespace of subscriber: wrong-ns are different",
                        },
                        "Status": <*matchers.EqualMatcher | 0xc000f16af0>{
                            Expected: <v1.ConditionStatus>"False",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/invalid_sink;_not_a_valid_cluster_local_service (10.03s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.000s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c1b30>: {
                    Fields: {
                        "Type": <*matchers.EqualMatcher | 0xc000f16b30>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16b50>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription not active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f16b70>{
                            Expected: <string>"failed to validate subscription sink URL. It is not a valid cluster local svc: Service \"testapp\" not found",
                        },
                        "Status": <*matchers.EqualMatcher | 0xc000f16b90>{
                            Expected: <v1.ConditionStatus>"False",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/valid_sink (10.03s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.000s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c1bf0>: {
                    Fields: {
                        "Type": <*matchers.EqualMatcher | 0xc000f16bd0>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16bf0>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f16c00>{Expected: <string>""},
                        "Status": <*matchers.EqualMatcher | 0xc000f16c20>{
                            Expected: <v1.ConditionStatus>"True",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/valid_sink;_with_port (10.03s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.001s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c1cb0>: {
                    Fields: {
                        "Type": <*matchers.EqualMatcher | 0xc000f16c80>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16ca0>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f16cb0>{Expected: <string>""},
                        "Status": <*matchers.EqualMatcher | 0xc000f16cd0>{
                            Expected: <v1.ConditionStatus>"True",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/valid_sink;_with_port_and_endpoint (10.03s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.000s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c1d70>: {
                    Fields: {
                        "Type": <*matchers.EqualMatcher | 0xc000f16d50>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16d70>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription active",
                        },
                        "Message": <*matchers.EqualMatcher | 0xc000f16d80>{Expected: <string>""},
                        "Status": <*matchers.EqualMatcher | 0xc000f16da0>{
                            Expected: <v1.ConditionStatus>"True",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
    --- FAIL: TestCreateSubscription/empty_protocol,_protocol_setting_and_dialect (10.03s)
        reconciler_internal_integration_test.go:289: creating the k8s subscription
        reconciler_internal_integration_test.go:291: testing the k8s subscription
        test_utils.go:98:
            Timed out after 10.000s.
            Failed to match the eventing subscription
            Expected
                <[]v1alpha1.Condition | len:0, cap:0>: nil
            to contain element matching
                <*gstruct.FieldsMatcher | 0xc0009c1e30>: {
                    Fields: {
                        "Message": <*matchers.EqualMatcher | 0xc000f16e10>{Expected: <string>""},
                        "Status": <*matchers.EqualMatcher | 0xc000f16e30>{
                            Expected: <v1.ConditionStatus>"True",
                        },
                        "Type": <*matchers.EqualMatcher | 0xc000f16de0>{
                            Expected: <v1alpha1.ConditionType>"Subscription active",
                        },
                        "Reason": <*matchers.EqualMatcher | 0xc000f16e00>{
                            Expected: <v1alpha1.ConditionReason>"NATS Subscription active",
                        },
                    },
                    IgnoreExtras: true,
                    IgnoreMissing: true,
                    failures: nil,
                }
2022/12/09 16:23:35 NATS server with JetStream started nats://127.0.0.1:49845
{"level":"ERROR","timestamp":"2022-12-09T16:23:36+01:00","logger":"jetstream-subscription-reconciler","caller":"jetstream/reconciler.go:135","message":"Failed to add finalizer to Subscription","context":{"kind":"Subscription","version":1,"namespace":"test","name":"nats-sub-0","error":"failed to add finalizer to subscription: Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused","errorVerbose":"failed to add finalizer to subscription:\n    github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream.(*Reconciler).addFinalizerToSubscription\n        /Users/faizan/git/mfaizanse/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler.go:248\n  - Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused"}}
{"level":"ERROR","timestamp":"2022-12-09T16:23:36+01:00","caller":"record/event.go:276","message":"Unable to write event: '&v1.Event{TypeMeta:v1.TypeMeta{Kind:\"\", APIVersion:\"\"}, ObjectMeta:v1.ObjectMeta{Name:\"nats-sub-10.172f294c804a0010\", GenerateName:\"\", Namespace:\"test\", SelfLink:\"\", UID:\"\", ResourceVersion:\"487\", Generation:0, CreationTimestamp:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), DeletionTimestamp:<nil>, DeletionGracePeriodSeconds:(*int64)(nil), Labels:map[string]string(nil), Annotations:map[string]string(nil), OwnerReferences:[]v1.OwnerReference(nil), Finalizers:[]string(nil), ManagedFields:[]v1.ManagedFieldsEntry(nil)}, InvolvedObject:v1.ObjectReference{Kind:\"Subscription\", Namespace:\"test\", Name:\"nats-sub-10\", UID:\"121623fa-469d-4975-a7d3-2171becbfd5e\", APIVersion:\"eventing.kyma-project.io/v1alpha1\", ResourceVersion:\"434\", FieldPath:\"\"}, Reason:\"UpdateFailed\", Message:\"Update Subscription status failed nats-sub-10\", Source:v1.EventSource{Component:\"eventing-controller-nats\", Host:\"\"}, FirstTimestamp:time.Date(2022, time.December, 9, 16, 23, 15, 0, time.Local), LastTimestamp:time.Date(2022, time.December, 9, 16, 23, 35, 934709000, time.Local), Count:22, Type:\"Warning\", EventTime:time.Date(1, time.January, 1, 0, 0, 0, 0, time.UTC), Series:(*v1.EventSeries)(nil), Action:\"\", Related:(*v1.ObjectReference)(nil), ReportingController:\"\", ReportingInstance:\"\"}': 'Patch \"https://127.0.0.1:64446/api/v1/namespaces/test/events/nats-sub-10.172f294c804a0010\": dial tcp 127.0.0.1:64446: connect: connection refused'(may retry after sleeping)\n","context":{}}
{"level":"ERROR","timestamp":"2022-12-09T16:23:37+01:00","logger":"jetstream-subscription-reconciler","caller":"jetstream/reconciler.go:135","message":"Failed to add finalizer to Subscription","context":{"kind":"Subscription","version":1,"namespace":"test","name":"nats-sub-0","error":"failed to add finalizer to subscription: Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused","errorVerbose":"failed to add finalizer to subscription:\n    github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream.(*Reconciler).addFinalizerToSubscription\n        /Users/faizan/git/mfaizanse/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler.go:248\n  - Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused"}}
{"level":"ERROR","timestamp":"2022-12-09T16:23:39+01:00","logger":"jetstream-subscription-reconciler","caller":"jetstream/reconciler.go:135","message":"Failed to add finalizer to Subscription","context":{"kind":"Subscription","version":1,"namespace":"test","name":"nats-sub-0","error":"failed to add finalizer to subscription: Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused","errorVerbose":"failed to add finalizer to subscription:\n    github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream.(*Reconciler).addFinalizerToSubscription\n        /Users/faizan/git/mfaizanse/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler.go:248\n  - Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused"}}
{"level":"ERROR","timestamp":"2022-12-09T16:23:41+01:00","logger":"jetstream-subscription-reconciler","caller":"jetstream/reconciler.go:135","message":"Failed to add finalizer to Subscription","context":{"kind":"Subscription","version":1,"namespace":"test","name":"nats-sub-0","error":"failed to add finalizer to subscription: Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused","errorVerbose":"failed to add finalizer to subscription:\n    github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream.(*Reconciler).addFinalizerToSubscription\n        /Users/faizan/git/mfaizanse/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler.go:248\n  - Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused"}}
{"level":"ERROR","timestamp":"2022-12-09T16:23:43+01:00","logger":"jetstream-subscription-reconciler","caller":"jetstream/reconciler.go:135","message":"Failed to add finalizer to Subscription","context":{"kind":"Subscription","version":1,"namespace":"test","name":"nats-sub-0","error":"failed to add finalizer to subscription: Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused","errorVerbose":"failed to add finalizer to subscription:\n    github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream.(*Reconciler).addFinalizerToSubscription\n        /Users/faizan/git/mfaizanse/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler.go:248\n  - Put \"https://127.0.0.1:62348/apis/eventing.kyma-project.io/v1alpha1/namespaces/test/subscriptions/nats-sub-0\": dial tcp 127.0.0.1:62348: connect: connection refused"}}
{"level":"ERROR","timestamp":"2022-12-09T16:23:44+01:00","caller":"jetstream/reconciler.go:63","message":"Failed to start reconciler","context":{"name":"jetstream-subscription-reconciler","error":"nats: stream configuration update can not change storage type"}}
--- FAIL: TestChangeSubscription (8.57s)
panic: nats: stream configuration update can not change storage type [recovered]
	panic: nats: stream configuration update can not change storage type

goroutine 4475 [running]:
testing.tRunner.func1.2({0x26c0720, 0xc000e8a640})
	/usr/local/Cellar/go/1.19.3/libexec/src/testing/testing.go:1396 +0x24e
testing.tRunner.func1()
	/usr/local/Cellar/go/1.19.3/libexec/src/testing/testing.go:1399 +0x39f
panic({0x26c0720, 0xc000e8a640})
	/usr/local/Cellar/go/1.19.3/libexec/src/runtime/panic.go:884 +0x212
github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream.NewReconciler({0x2bec1e8?, 0xc000807500}, {0x2bf4f48?, 0xc000bcf4a0}, {0x2bef038?, 0xc000034580}, 0xc000688af8, {0x2beb120?, 0xc000cb24c0}, {0x2bd4460, ...}, ...)
	/Users/faizan/git/mfaizanse/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler.go:64 +0x473
github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream_test.startReconciler({0x28e54af, 0x6}, 0xc00110c618)
	/Users/faizan/git/mfaizanse/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_integration_test.go:794 +0xb8d
github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream_test.setupTestEnsemble({0x2bec220?, 0xc00018e008}, {0x28e54af, 0x6}, 0xc00083af90, 0x0?)
	/Users/faizan/git/mfaizanse/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_integration_test.go:729 +0x3b2
github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream_test.TestChangeSubscription(0xc00086d6c0)
	/Users/faizan/git/mfaizanse/kyma/components/eventing-controller/controllers/subscription/jetstream/reconciler_internal_integration_test.go:321 +0x218
testing.tRunner(0xc00086d6c0, 0x29ee530)
	/usr/local/Cellar/go/1.19.3/libexec/src/testing/testing.go:1446 +0x10b
created by testing.(*T).Run
	/usr/local/Cellar/go/1.19.3/libexec/src/testing/testing.go:1493 +0x35f
FAIL	github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/jetstream	185.522s
?   	github.com/kyma-project/kyma/components/eventing-controller/controllers/subscription/testing	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/controllers/subscriptionv2/eventmesh	128.531s	coverage: 81.2% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/controllers/subscriptionv2/eventmesh/test	56.678s	coverage: 82.5% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/controllers/subscriptionv2/jetstream	130.413s	coverage: 84.9% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/controllers/subscriptionv2/reconcilertesting	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/logger	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/options	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/application	0.689s	coverage: 29.6% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/application/applicationtest	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/application/fake	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/beb	1.430s	coverage: 51.4% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/beb/mocks	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/cleaner	0.821s	coverage: 100.0% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/eventmesh	2.745s	coverage: 82.5% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/eventmesh/mocks	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/eventtype	0.917s	coverage: 96.9% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/jetstreamv2	82.237s	coverage: 81.0% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/jetstreamv2/mocks	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/metrics	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/nats	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/nats/jetstream	273.577s	coverage: 75.8% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/nats/jetstream/mocks	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/nats/testing	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/sink	4.464s	coverage: 91.2% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/sink/v2	4.103s	coverage: 78.6% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/utils	3.938s	coverage: 68.5% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/backend/utils/v2	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/constants	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/deployment	2.481s	coverage: 92.7% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/ems/api/events/client	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/ems/api/events/client/mocks	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/ems/api/events/types	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/ems/auth	0.972s	coverage: 100.0% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/ems/httpclient	0.422s	coverage: 31.7% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/env	1.101s	coverage: 58.8% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/informers	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/object	5.029s	coverage: 56.5% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/object/v2	1.287s	coverage: 15.2% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/signals	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/pkg/subscriptionmanager	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/subscriptionmanager/beb	3.010s	coverage: 33.5% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/subscriptionmanager/jetstream	16.371s	coverage: 18.2% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/pkg/tracing	1.242s	coverage: 100.0% of statements
ok  	github.com/kyma-project/kyma/components/eventing-controller/testing	3.386s	coverage: 0.2% of statements
?   	github.com/kyma-project/kyma/components/eventing-controller/testing/event/cehelper	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/testing/nats	[no test files]
?   	github.com/kyma-project/kyma/components/eventing-controller/testing/v2	[no test files]
ok  	github.com/kyma-project/kyma/components/eventing-controller/utils	0.590s	coverage: 84.2% of statements
FAIL
make: *** [go-test] Error 1
```
