### ISSUE TITLE
Failing unstable-cli on fast integration standard test suite

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#16927]
**Description**
The pipeline [unstable-cli](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/unstable-cli) is failing consistently on fast integration standard test suite.

**Expected result**
Fast integration standard test suite should succeed

**Actual result**
Fast integration standard test suite is failing:
```log
1) Executing Standard Testsuite:
       "before all" hook: CommerceMock test fixture should be ready in "Executing Standard Testsuite:":
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Failing Run link**:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/unstable-cli/1630116895577346048

**Comment by a-thaler** [comment]
Was not able to reproduce it with latest versions, recent job run proceeeded as well, so I will close the ticket
