### ISSUE TITLE
Failing kyma-upgrade-k3d-kyma2-to-main on fast integration tests' upgrade test preparation phase

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#16926]
**Description**
The pipeline [kyma-upgrade-k3d-kyma2-to-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main) is failing consistently on fast integration tests' upgrade test preparation phase.

**Expected result**
Fast integration tests' upgrade test preparation phase should succeed

**Actual result**
Fast integration tests' upgrade test preparation phase is failing:
```log
1) Upgrade test preparation
       CommerceMock test fixture should be ready:
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

**Failing Run link**:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1630115698069999616

**Comment by a-thaler** [comment]
It is very green now for several runs, closing the issue
