### ISSUE TITLE
Failing `nightly-main-reconciler-e2e` on Prometheus Tests

### ISSUE THREAD

**Issue by khlifi411** [kyma-project/kyma#16966]
**Description**
The pipeline [nightly-main-reconciler-e2e](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e) is failing consistently on the Prometheus test suite.

**Expected result**
Prometheus test suite should succeed

**Actual result**
Prometheus test suite is failing:
```log
25 passing (5m)
  1 failing

  1) Executing Standard Testsuite:
       Prometheus Tests:
         Prometheus targets should be healthy:
     AssertionError: Following targets are unhealthy: tracing-jaeger-metrics: Get "https://100.96.0.26:14269/metrics": context deadline exceeded: expected [ 'tracing-jaeger-metrics: Get "https://100.96.0.26:14269/metrics": context deadline exceeded' ] to be empty
      at Object.assertAllTargetsAreHealthy (monitoring/prometheus.js:57:10)
      at async Context.<anonymous> (monitoring/index.js:40:7)
```

**Failing Run link**:
https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/nightly-main-reconciler-e2e/1631187724276862976

**Comment by khlifi411** [comment]
Closing as pipeline is consistently green again.
