### ISSUE TITLE
admission webhook validation.webhook.serverless.kyma-project.io denied the request: nodejs18 is not supported

### ISSUE THREAD

**Issue by ruanxin** [kyma-project/kyma#17049]
**Description**

[pre-main-control-plane-reconciler-e2e-latest-release](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release) pipeline failed because of fast integration test error.

```
  Executing Standard Testsuite:
[ERROR] HttpError: HTTP request failed
    1) "before all" hook: CommerceMock test fixture should be ready in "Executing Standard Testsuite:"


  0 passing (35s)
  1 failing

  1) Executing Standard Testsuite:
       "before all" hook: CommerceMock test fixture should be ready in "Executing Standard Testsuite:":
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

```

Enabled fast integration debug mode, the root cause is admission webhook \"validation.webhook.serverless.kyma-project.io\" denied the request: validation failed: [spec.runtime contains unsupported value invalid source.inline.dependencies value: cannot find runtime: nodejs18

```
[DEBUG] {
    "response": {
        "statusCode": 403,
        "body": {
            "kind": "Status",
            "apiVersion": "v1",
            "metadata": {},
            "status": "Failure",
            "message": "admission webhook \"validation.webhook.serverless.kyma-project.io\" denied the request: validation failed: [spec.runtime contains unsupported value invalid source.inline.dependencies value: cannot find runtime: nodejs18]",
            "reason": "validation failed: [spec.runtime contains unsupported value invalid source.inline.dependencies value: cannot find runtime: nodejs18]",
            "code": 403
        },
        "headers": {
            "audit-id": "439d6041-eafa-42d4-9257-6c0a62a3890c",
            "cache-control": "no-cache, private",
            "content-type": "application/json",
            "x-kubernetes-pf-flowschema-uid": "b67df667-5cdc-4cf0-80c0-4e8beb1abf78",
            "x-kubernetes-pf-prioritylevel-uid": "17a7f885-b7fc-4ff9-acff-534186dfa645",
            "date": "Fri, 10 Mar 2023 12:07:42 GMT",
            "content-length": "457",
            "connection": "close"
        },
        "request": {
            "uri": {
                "protocol": "https:",
                "slashes": true,
                "auth": null,
                "host": "api.grdxvi24c.kyma-prow.shoot.live.k8s-hana.ondemand.com",
                "port": 443,
                "hostname": "api.grdxvi24c.kyma-prow.shoot.live.k8s-hana.ondemand.com",
                "hash": null,
                "search": null,
                "query": null,
                "pathname": "/apis/serverless.kyma-project.io/v1alpha2/namespaces/test/functions",
                "path": "/apis/serverless.kyma-project.io/v1alpha2/namespaces/test/functions",
                "href": "https://api.grdxvi24c.kyma-prow.shoot.live.k8s-hana.ondemand.com/apis/serverless.kyma-project.io/v1alpha2/namespaces/test/functions"
            },
            "method": "POST",
            "headers": {
                "accept": "application/json",
                "Authorization": "Bearer 0x8H70du67RDnR64qiZrgBdp5DhxJAtnos3qiXtJseapxJTPFZnSwf4B8xhFTALKDI2Zgq969NgzbXerctFWPhuGJPBxnHipQsAxk20B9zUYIH3XYbAuJYfpL8inwe1A",
                "content-type": "application/json",
                "content-length": 6015
            }
        }
    },
    "body": {
        "kind": "Status",
        "apiVersion": "v1",
        "metadata": {},
        "status": "Failure",
        "message": "admission webhook \"validation.webhook.serverless.kyma-project.io\" denied the request: validation failed: [spec.runtime contains unsupported value invalid source.inline.dependencies value: cannot find runtime: nodejs18]",
        "reason": "validation failed: [spec.runtime contains unsupported value invalid source.inline.dependencies value: cannot find runtime: nodejs18]",
        "code": 403
    },
    "statusCode": 403,
    "name": "HttpError"
}
```

**Comment by ruanxin** [comment]
This failing should be related to this issue https://github.com/kyma-project/kyma/pull/16918,  keep this ticket open until next release, assume it will be fixed.
