### ISSUE TITLE
Prow job pre-main-kyma-gardener-gcp-eventing-upgrade is failing more then 50% of the time

### ISSUE THREAD

**Issue by barchw** [kyma-project/kyma#17146]
**Description**

The job `pre-main-kyma-gardener-gcp-eventing-upgrade` is flaky and failing often. As there is a dependency to api-gateway image from eventing, this job is blocking https://github.com/kyma-project/kyma/pull/17132.

**Expected result**
The job finishes successfully

**Troubleshooting**
The job seems to be using `serverless` and `APIRule` in deprecated `v1alpha1` version. This might be causing some problems.

**Comment by muralov** [comment]
The most common issue appears during upgrade step:

Deployed Components: 5/8

```yaml
Could not deploy the following components:

- monitoring
- telemetry
- tracing
```

Deployed Components: 5/8

```yaml
Could not deploy the following components:

- monitoring
- tracing
- ory
```

Deployed Components: 4/8

```yaml
Could not deploy the following components:

- telemetry
- monitoring
- serverless
- eventing
```

The job links:

[https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/17203/pre-main-kyma-gardener-gcp-eventing-upgrade/1641684165323657216/build-log.txt](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/17203/pre-main-kyma-gardener-gcp-eventing-upgrade/1641684165323657216/build-log.txt)

[https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/17217/pre-main-kyma-gardener-gcp-eventing-upgrade/1641690710312751104/build-log.txt](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/17217/pre-main-kyma-gardener-gcp-eventing-upgrade/1641690710312751104/build-log.txt)

[https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/17192/pre-main-kyma-gardener-gcp-eventing-upgrade/1641770154616426496/build-log.txt](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/17192/pre-main-kyma-gardener-gcp-eventing-upgrade/1641770154616426496/build-log.txt)

Second most common error:

```yaml
16 passing (3m)
  12 pending
  1 failing
  1) Eventing tests
       with BEB backend
         Cloud Events [binary] with v1alpha1 subscription should be delivered to eventing-sink :
     Error: Fetching published event responded with error: AssertionError: expected false to equal true
      at convertAxiosError (utils/index.js:104:12)
      at /root/.kyma_old/tests/fast-integration/eventing-test/utils.js:490:15
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async ensureEventReceivedWithRetry (eventing-test/utils.js:445:10)
      at async checkEventDelivery (eventing-test/utils.js:386:19)
      at async Context.<anonymous> (eventing-test/eventing-test.js:182:9)
```

third most common error:

```yaml
35 passing (8m)
  12 pending
  1 failing
  1) Eventing tests
       with Nats backend switched back from BEB
         Test jetStream at-least once delivery during kyma upgrade
           Pre-upgrade tasks to publish event which should not be delivered
             Deploy eventing-upgrade-sink:
     Error: Waiting for eventing-upgrade-sink function timeout (300000 ms)
      at Timeout._onTimeout (utils/index.js:335:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Comment by mfaizanse** [comment]
**Follow-up tasks:**
- [ ] Enable `consumerNotRecreated` and `atleastOnceDuringUpgrade` tests after adding stability. (disabled by this [PR](https://github.com/kyma-project/test-infra/pull/7074)).

**Comment by mfaizanse** [comment]
Job run with verbose logs: https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/17244/mfaizanse_test_of_prowjob_pre-main-kyma-gardener-gcp-eventing-u/1646114500077686784

**Comment by mfaizanse** [comment]
I am noticing the pattern, that during upgrade the pods are taking 3-4 mins with this error with state: FailedPostStartHook.
Even after - Component 'istio' deployed  msg.

```
Events:
  Type     Reason               Age    From               Message
  ----     ------               ----   ----               -------
  Normal   Scheduled            4m     default-scheduler  Successfully assigned kyma-system/tracing-jaeger-64c6557f67-wtjx8 to shoot--kyma-prow--grdjgxbgy-cpu-worker-z1-549bc-hld92
  Normal   Pulled               2m29s  kubelet            Container image "eu.gcr.io/kyma-project/external/istio/proxyv2:1.17.1-distroless" already present on machine
  Normal   Created              2m29s  kubelet            Created container istio-validation
  Normal   Started              2m29s  kubelet            Started container istio-validation
  Normal   Killing              88s    kubelet            FailedPostStartHook
  Warning  FailedPostStartHook  88s    kubelet            Exec lifecycle hook ([pilot-agent wait]) for Container "istio-proxy" in Pod "tracing-jaeger-64c6557f67-wtjx8_kyma-system(6b048195-da73-4d46-a8d9-2ba87100e098)" failed - error: command 'pilot-agent wait' exited with 255: Error: timeout waiting for Envoy proxy to become ready. Last error: Get "http://localhost:15021/healthz/ready": dial tcp [::1]:15021: connect: connection refused
, message: "2023-04-06T11:27:33.748663Z\tinfo\tWaiting for Envoy proxy to be ready (timeout: 60 seconds)...\n2023-04-06T11:28:33.749876Z\terror\ttimeout waiting for Envoy proxy to become ready. Last error: Get \"http://localhost:15021/healthz/ready\": dial tcp [::1]:15021: connect: connection refused\nError: timeout waiting for Envoy proxy to become ready. Last error: Get \"http://localhost:15021/healthz/ready\": dial tcp [::1]:15021: connect: connection refused\n"
  Normal   Pulled               83s                  kubelet  Container image "eu.gcr.io/kyma-project/external/jaegertracing/all-in-one:1.37.0" already present on machine
  Normal   Created              83s                  kubelet  Created container jaeger
  Normal   Started              82s (x2 over 2m28s)  kubelet  Started container istio-proxy
  Normal   Created              82s (x2 over 2m28s)  kubelet  Created container istio-proxy
  Normal   Pulled               82s (x2 over 2m28s)  kubelet  Container image "eu.gcr.io/kyma-project/external/istio/proxyv2:1.17.1-distroless" already present on machine
  Normal   Started              82s                  kubelet  Started container jaeger
  Warning  Unhealthy            30s (x6 over 80s)    kubelet  Readiness probe failed: Get "http://100.64.2.35:15020/app-health/jaeger/readyz": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy            30s (x4 over 75s)    kubelet  Liveness probe failed: Get "http://100.64.2.35:15020/app-health/jaeger/livez": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  FailedPostStartHook  22s                  kubelet  Exec lifecycle hook ([pilot-agent wait]) for Container "istio-proxy" in Pod "tracing-jaeger-64c6557f67-wtjx8_kyma-system(6b048195-da73-4d46-a8d9-2ba87100e098)" failed - error: command 'pilot-agent wait' exited with 255: Error: timeout waiting for Envoy proxy to become ready. Last error: Get "http://localhost:15021/healthz/ready": dial tcp [::1]:15021: connect: connection refused
, message: "2023-04-06T11:28:39.974485Z\tinfo\tWaiting for Envoy proxy to be ready (timeout: 60 seconds)...\n2023-04-06T11:29:39.974974Z\terror\ttimeout waiting for Envoy proxy to become ready. Last error: Get \"http://localhost:15021/healthz/ready\": dial tcp [::1]:15021: connect: connection refused\nError: timeout waiting for Envoy proxy to become ready. Last error: Get \"http://localhost:15021/healthz/ready\": dial tcp [::1]:15021: connect: connection refused\n"
```

For example: This time the upgrade took 15 mins.

![image](https://user-images.githubusercontent.com/9897945/231706826-18b923c3-5787-4154-ad98-c963e0d87ea0.png)

**Comment by mfaizanse** [comment]
Potential fix for failing upgrade: https://github.com/kyma-incubator/reconciler/pull/1336

**Comment by mfaizanse** [comment]
PR: https://github.com/kyma-project/kyma/pull/17312

**Comment by mfaizanse** [comment]
Job seems much stable now!
![image](https://user-images.githubusercontent.com/9897945/233615945-a8a976bc-cb03-4340-867d-1a37c3ec4d7b.png)

**Comment by mfaizanse** [comment]
Follow-up tickets:
- https://github.com/kyma-project/kyma/issues/17367
- https://github.com/kyma-project/kyma/issues/17368
