### ISSUE TITLE
Serverless controller crashes when function is created too early

### ISSUE THREAD

**Issue by pbochynski** [kyma-project/kyma#17147]
**Description**

Controller can't handle functions created before controller was started.

**Expected result**

Controller is resilient and can handle such situations.

**Actual result**

Panic:
```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x1328969]

goroutine 334 [running]:
github.com/kyma-project/kyma/components/function-controller/internal/controllers/serverless.(*systemState).buildDeployment(_, {{0xc0001fa0c0, 0x52}, {0xc000050125, 0x4e}, {0xc000052026, 0x49}, {0xc000052095, 0x45}, {0xc00004a065, ...}})
        /workspace/go/src/github.com/kyma-project/kyma/components/function-controller/internal/controllers/serverless/system_state.go:418 +0x8c9
github.com/kyma-project/kyma/components/function-controller/internal/controllers/serverless.stateFnCheckDeployments({0x18ab7d8, 0xc00032ebd0}, 0xc00031da20, 0xc000764900)
        /workspace/go/src/github.com/kyma-project/kyma/components/function-controller/internal/controllers/serverless/deployment.go:50 +0x2e5
github.com/kyma-project/kyma/components/function-controller/internal/controllers/serverless.(*reconciler).reconcile(_, {_, _}, {{{0x13951ed, 0x8}, {0xc0001e8870, 0x23}}, {{0xc0006d3a70, 0x7}, {0x0, ...}, ...}, ...})
        /workspace/go/src/github.com/kyma-project/kyma/components/function-controller/internal/controllers/serverless/fsm.go:68 +0x239
github.com/kyma-project/kyma/components/function-controller/internal/controllers/serverless.(*FunctionReconciler).Reconcile(0xc000126780, {0x18ab7d8, 0xc00032ebd0}, {{{0xc0006d3a80?, 0x15c4ae0?}, {0xc0006d3a70?, 0x30?}}})
        /workspace/go/src/github.com/kyma-project/kyma/components/function-controller/internal/controllers/serverless/function_reconcile.go:157 +0x791
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0xc00053a210, {0x18ab7d8, 0xc00032eb10}, {{{0xc0006d3a80?, 0x15c4ae0?}, {0xc0006d3a70?, 0x417794?}}})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:114 +0x28b
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc00053a210, {0x18ab730, 0xc000088a80}, {0x150d160?, 0xc000335160?})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:311 +0x352
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem(0xc00053a210, {0x18ab730, 0xc000088a80})
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:266 +0x1d9
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2()
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:227 +0x85
created by sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2
        /go/pkg/mod/sigs.k8s.io/controller-runtime@v0.11.2/pkg/internal/controller/controller.go:223 +0x31c
```

**Steps to reproduce**
Follow this scenario: https://killercoda.com/kyma-project/scenario/serverless
but do not wait until Serverless module is in the state ready and create function immediately after creating Serverless resource.

**Comment by kwiatekus** [comment]
unexpected nil value comes from the fact that in this scenario defaulting webhook was not yet up and running and invalid (not defaulted) function CR has passed through the admission process.

**Comment by pbochynski** [comment]
To be honest I do not like the solution. First of all user now is exposed to the problem that webhook starts slowly and crashes 2 times before can handle requests. Until it is fully stable I had to try 3 times to create the function and I saw such ugly error:
```
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/kwiatekus/serverless-keda-demo/main/demo-app/fibo-fn.yaml": Internal error occurred: failed calling webhook "defaulting.webhook.serverless.kyma-project.io": failed to call webhook: Post "https://serverless-webhook.kyma-system.svc:443/defaulting/functions?timeout=10s": dial tcp 10.99.17.48:443: connect: connection refused
```
The fourth time it finally worked. 
So If I have my application that is based on serverless I cannot use declarative approach and declare my functions in front. I need to wait until webhook is up and running to deploy my application. 

It looks like function controller just adds some default values. Maybe it doesn't have to be webhook at all. You can define even complex default value in json schema. Kubebuilder supports it: https://book.kubebuilder.io/reference/markers.html?highlight=kubebuilder:default#marker-syntax
