### ISSUE TITLE
Several pipelines fail on CommerceMock timeout

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#17151]
**Description**

The following pipelines are failing:

- [kyma-upgrade-k3d-kyma2-to-main](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main)
- [pre-main-control-plane-reconciler-e2e-latest-release](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-e2e-latest-release)
- [pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener)

**Expected result**

The pipelines are completing without errors

**Actual result**

The error reported looks like:
```
[ERROR] Error: Waiting for lastorder function timeout (90000 ms)
    1) CommerceMock test fixture should be ready


  0 passing (2m)
  1 failing

  1) Upgrade test preparation
       CommerceMock test fixture should be ready:
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

or

```
[ERROR] Error: Waiting for lastorder function timeout (90000 ms)
    1) "before all" hook: CommerceMock test fixture should be ready in "Executing Standard Testsuite:"


  0 passing (2m)
  1 failing

  1) Executing Standard Testsuite:
       "before all" hook: CommerceMock test fixture should be ready in "Executing Standard Testsuite:":
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)
```

or 

```
[ERROR] Error: Waiting for lastorder function timeout (90000 ms)
    1) CommerceMock test fixture should be ready


  0 passing (3m)
  1 failing

  1) Upgrade test preparation
       CommerceMock test fixture should be ready:
     Error: Waiting for lastorder function timeout (90000 ms)
      at Timeout._onTimeout (utils/index.js:335:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)
```

**Steps to reproduce**

n/a

**Troubleshooting**

n/a

**Comment by a-thaler** [comment]
Most probably related to https://github.com/kyma-project/kyma/pull/17090

**Comment by dbadura** [comment]
Could you check those tests again?

**Comment by dbadura** [comment]
`kyma-upgrade-k3d-kyma2-to-main` is green
