### ISSUE TITLE
pre-main-control-plane-reconciler-* pipelines failing at logging tests

### ISSUE THREAD

**Issue by lindnerby** [kyma-project/kyma#17379]
**Description**

Pipelines `pre-main-control-plane-reconciler-e2e-latest-release` and `pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener` are failing on _Executing Standard Testsuite -> Logging Tests_ due to an expected field in istio access log not being present.

Example jobs from history:
* [pre-main-control-plane-reconciler-e2e-latest-release](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2696/pre-main-control-plane-reconciler-e2e-latest-release/1650484951134507008)
* [pre-main-control-plane-reconciler-e2e-latest-release](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2696/pre-main-control-plane-reconciler-e2e-latest-release/1649397732424552448)
* [pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2678/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1650421339011420160)
* [pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2670/pre-main-control-plane-reconciler-upgrade-kyma2-latest-to-main-gardener/1650400417609158656)

**Expected result**

Should succeed.

**Actual result**

Failing with:
```
1) Executing Standard Testsuite:
       Logging Tests:
         Istio Access Logs tests
           Should query Loki and verify format of Istio Access Logs:
     AssertionError: Istio access log does not have 'traceparent' field: [object Object]: expected undefined to not equal undefined
      
at verifyLogAttributeIsPresent (logging/loki.js:97:10)
      at Object.verifyIstioAccessLogFormat (logging/loki.js:92:3)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (logging/index.js:57:7)
```
**Steps to reproduce**

**Troubleshooting**

**Comment by rakesh-garimella** [comment]
Checked the `[pre-main-control-plane-reconciler-e2e-latest-release](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2718/pre-main-control-plane-reconciler-e2e-latest-release/1653284538266161152/build-log.txt) here the problem is the tests from main are being executed against kyma version 2.13.1 which is wrong. The tests from kyma version 2.13.1 should be executed again kyma version 2.13.1

**Comment by Tomasz-Smelcerz-SAP** [comment]
@rakesh-garimella I have tested the simpler pipeline: `pre-main-control-plane-reconciler-e2e-latest-release`. There's no upgrade there, just testing the `latest` Kyma. Which is `2.13.1` at the moment.
I implemented the change you suggested: Switching the tests to the same kyma version: `2.13.1`.

The tests now [fail with another error](https://storage.googleapis.com/kyma-prow-logs/pr-logs/pull/kyma-project_control-plane/2742/tomasz-smelcerz-sap_test_of_prowjob_pre-main-control-plane-reco/1656175894793818112/build-log.txt):

```
   Tracing Tests:
      with Nats backend
        ✓ Wait until subscriptions are ready
        1) in-cluster structured event should have correct tracing spans


  25 passing (3m)
  1 failing

  1) Executing Standard Testsuite:
       Tracing Tests:
         with Nats backend
           in-cluster structured event should have correct tracing spans:
     Error: cannot get jaeger trace
404: Not Found: {"message":"Data source not found"}
      at convertAxiosError (utils/index.js:126:10)
      at getJaegerTrace (tracing/client.js:29:11)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async checkTrace (test/fixtures/commerce-mock/index.js:351:20)
      at async checkInClusterEventTracing (test/fixtures/commerce-mock/index.js:347:3)
      at async Context.<anonymous> (tracing/index.js:30:9)
```

Just for comparison, the unmodified pipeline (tests from `main` branch) fails differently:
```
 1) Executing Standard Testsuite:
       Logging Tests:
         Istio Access Logs tests
           Should query Loki and verify format of Istio Access Logs:
     AssertionError: Istio access log does not have 'traceparent' field: {"_p":"F","authority":"logging-loki:3100","bytes_received":9072,"bytes_sent":0,"cluster_identifier":"api.grd4xr5z2.kyma-prow.internal.live.k8s.ondemand.com","connection_termination_details":null,"downstream_local_address":"100.96.2.9:3100","downstream_remote_address":"100.96.2.37:52964","duration":1,"log":"{\"authority\":\"logging-loki:3100\",\"downstream_local_address\":\"100.96.2.9:3100\",\"path\":\"/loki/api/v1/push\",\"method\":\"POST\",\"x_forwarded_for\":null,\"bytes_received\":9072,\"upstream_transport_failure_reason\":null,\"response_flags\":\"-\",\"user_agent\":\"promtail/\",\"connection_termination_details\":null,\"duration\":1,\"protocol\":\"HTTP/1.1\",\"downstream_remote_address\":\"100.96.2.37:52964\",\"response_code_details\":\"via_upstream\",\"request_id\":\"c988eefd-7ff8-9a0e-ad13-54b813979750\",\"bytes_sent\":0,\"requested_server_name\":\"outbound_.3100_._.logging-loki.kyma-system.svc.cluster.local\",\"upstream_cluster\":\"inbound|3100||\",\"upstream_service_time\":\"1\",\"start_time\":\"2023-05-10T06:14:36.672Z\",\"response_code\":204,\"upstream_host\":\"100.96.2.9:3100\",\"upstream_local_address\":\"127.0.0.6:46289\",\"route_name\":\"default\"}","method":"POST","path":"/loki/api/v1/push","protocol":"HTTP/1.1","request_id":"c988eefd-7ff8-9a0e-ad13-54b813979750","requested_server_name":"outbound_.3100_._.logging-loki.kyma-system.svc.cluster.local","response_code":204,"response_code_details":"via_upstream","response_flags":"-","route_name":"default","start_time":"2023-05-10T06:14:36.672Z","stream":"stdout","time":"2023-05-10T06:14:36.770967172Z","upstream_cluster":"inbound|3100||","upstream_host":"100.96.2.9:3100","upstream_local_address":"127.0.0.6:46289","upstream_service_time":"1","upstream_transport_failure_reason":null,"user_agent":"promtail/","x_forwarded_for":null}: expected undefined to not equal undefined
      at verifyLogAttributeIsPresent (logging/loki.js:122:10)
      at accessLogVerified (logging/loki.js:113:7)
      at Object.verifyIstioAccessLogFormat (logging/loki.js:64:9)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async Context.<anonymous> (logging/index.js:45:7)
```
