### ISSUE TITLE
pre-main-kyma-gardener-gcp-eventing-upgrade is flaky

### ISSUE THREAD

**Issue by friedrichwilken** [kyma-project/kyma#17431]
**Description**

[pre-main-kyma-gardener-gcp-eventing-upgrade ](https://status.build.kyma-project.io/job-history/gs/kyma-prow-logs/pr-logs/directory/pre-main-kyma-gardener-gcp-eventing-upgrade) is flaky.

a reappearing reason is an issues with the  `eventing-nats-apirule`

```
  1) Eventing tests
       "before all" hook: Create an ApiRule for NATS in "Eventing tests":
     Error: Wait for VirtualService eventing-nats-apirule timeout (30000 ms)
      at Timeout._onTimeout (utils/index.js:345:20)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7
```

**Expected result**

test works reliable

**Actual result**

test works is flaky

**Steps to reproduce**

run test

**Troubleshooting**

**Comment by k15r** [comment]
minimize external dependencies 
- serverless 
- remove api-rule for nats (replace with ???)

**Comment by mfaizanse** [comment]
Ignore unnecessary folders as trigger points for this job:
- https://github.com/kyma-project/kyma/tree/main/tests/fast-integration

**Comment by k15r** [comment]
https://xkcd.com/208/
