### ISSUE TITLE
Multiple pipelines are failing due to the error: cannot query loki 404: Not Found: {"message":"Data source not found"}

### ISSUE THREAD

**Issue by Tomasz-Smelcerz-SAP** [kyma-project/kyma#17755]
**Description**

I can observe this in the following pipelines:
- kyma-upgrade-k3d-kyma2-to-main
  - [example 1](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1673934291081367552)
  - [example 2](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1673753288488521728)
  - [example 3](https://status.build.kyma-project.io/view/gs/kyma-prow-logs/logs/kyma-upgrade-k3d-kyma2-to-main/1673723089168371712)
- kyma-upgrade-gardener-kyma2-to-main-reconciler-main
  - [example 1](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1673753288274612224/build-log.txt)
  - [example 2](https://storage.googleapis.com/kyma-prow-logs/logs/kyma-upgrade-gardener-kyma2-to-main-reconciler-main/1673723088962850816/build-log.txt)

**Expected result**

The tests are passing

**Actual result**
```
  17 passing (1m)
  4 failing

  1) Upgrade test tests
       Logging Tests:
         Check Loki logs from kyma-system namespace:
     Error: cannot query loki
404: Not Found: {"message":"Data source not found"}
      at convertAxiosError (utils/index.js:126:10)
      at queryLoki (logging/client.js:52:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async logsPresentInLoki (logging/client.js:24:26)
      at async Object.checkKymaLogs (logging/loki.js:34:33)
      at async Context.<anonymous> (logging/index.js:21:7)

  2) Upgrade test tests
       Logging Tests:
         Should exclude fluent-bit logs:
     Error: cannot query loki
404: Not Found: {"message":"Data source not found"}
      at convertAxiosError (utils/index.js:126:10)
      at queryLoki (logging/client.js:52:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async logsPresentInLoki (logging/client.js:24:26)
      at async Object.checkFluentBitLogs (logging/loki.js:42:32)
      at async Context.<anonymous> (logging/index.js:25:7)

  3) Upgrade test tests
       Logging Tests:
         Retention Period and Max look-back Period should be 120h:
     HttpError: HTTP request failed
      at Request._callback (node_modules/@kubernetes/client-node/dist/object.js:416:32)
      at Request.self.callback (node_modules/request/request.js:185:22)
      at Request.<anonymous> (node_modules/request/request.js:1154:10)
      at IncomingMessage.<anonymous> (node_modules/request/request.js:1076:12)
      at endReadableNT (internal/streams/readable.js:1333:12)
      at processTicksAndRejections (internal/process/task_queues.js:82:21)

  4) Upgrade test tests
       Logging Tests:
         Istio Access Logs tests
           Should query Loki and verify format of Istio Access Logs:
     Error: cannot query loki
404: Not Found: {"message":"Data source not found"}
      at convertAxiosError (utils/index.js:126:10)
      at queryLoki (logging/client.js:52:11)
      at runMicrotasks (<anonymous>)
      at processTicksAndRejections (internal/process/task_queues.js:95:5)
      at async logsPresentInLoki (logging/client.js:24:26)
      at async Object.verifyIstioAccessLogFormat (logging/loki.js:67:29)
      at async Context.<anonymous> (logging/index.js:49:7)

```

**Comment by rakesh-garimella** [comment]
The problem here is in 2.15.1 there was no loki resource being deployed in `upgrade-preparation` step. And after upgrade we use the new loki resource for querying and it fails. So to work around install the new loki resource after upgrade as we would use this as datasource.

The test kyma-upgrade-k3d-kyma2-to-main  [passes](https://storage.googleapis.com/kyma-prow-logs/logs/rakesh-garimella_test_of_prowjob_kyma-upgrade-k3d-kyma2-to-main/1676160089465032704/build-log.txt).

However `kyma-upgrade-gardener-kyma2-to-main-reconciler-main` is still failing although In the pjTester I dont see the step `Deploys the Loki resource (20420ms)`. I assume somehow its still using the latest main but not inculding chages from my PR. 

I will merge the PR and see again if after merge the test still fails.

**Comment by rakesh-garimella** [comment]
The last run of PJtest[kyma-upgrade-gardener-kyma2-to-main-reconciler-main](https://storage.googleapis.com/kyma-prow-logs/logs/rakesh-garimella_test_of_prowjob_kyma-upgrade-gardener-kyma2-to/1676225116247166976/build-log.txt) also passed so closing the issue
