### ISSUE TITLE
Service Bindings created with prefix created in Lambda UI not usable

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#2324]
**Steps to Reproduce**
1. Create a lambda that will make a call to an API of external solution.
1. Define the URL as `var url = `${process.env.ses-GATEWAY_URL}/electronics/orders/${orderId}`;`
1. Create Service Binding with `ses` as prefix.
1. Trigger the lambda via event or http.
1. Lambda will fail with  following error:

```
Function failed to execute: ReferenceError: GATEWAY_URL is not defined
    at main (/kubeless/handler.js:8:34)
    at modExecute (/kubeless_rt/kubeless.js:96:25)
    at /kubeless_rt/kubeless.js:57:29
    at /kubeless/handler.js:2:20
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at app.all (/kubeless_rt/kubeless.js:156:20)
    at Layer.handle [as handle_request] (/kubeless_rt/node_modules/express/lib/router/layer.js:95:5)
    at next (/kubeless_rt/node_modules/express/lib/router/route.js:137:13)
    at next (/kubeless_rt/node_modules/express/lib/router/route.js:131:14)
```

on inspecting the environment, following were oberved
**Lambda + Service Binding + Prefix**
notice quotes in 
```
NODE_PATH: '/kubeless/node_modules',
'ses-GATEWAY_URL': 'http://app-sample-external-soluti-583a8723-ab4a-44fe-8aaf-43ee69bf8610.kyma-integration.svc.cluster.local',
FUNC_HANDLER: 'main',
```

**Lamabda + Service Binding + No-prefix**
Proper variable defined
```
NODE_PATH: '/kubeless/node_modules',
GATEWAY_URL: 'http://app-sample-external-soluti-583a8723-ab4a-44fe-8aaf-43ee69bf8610.kyma-integration.svc.cluster.local',
FUNC_RUNTIME: 'nodejs8',
```
Also, there seems to be inconsistency when
**Service Binding is created from the catalog UI**
No `-` and no quotes
```
NODE_PATH: '/kubeless/node_modules',
KUBELESS_INSTALL_VOLUME: '/kubeless',
sesGATEWAY_URL: 'http://app-sample-external-soluti-583a8723-ab4a-44fe-8aaf-43ee69bf8610.kyma-integration.svc.cluster.local',
MOD_NAME: 'handler',
FUNC_TIMEOUT: '180',
```

**Comment by joek** [comment]
This is a nodejs related issue. If you reference the variable using ```process.env['foo-HOST']``` it is working like expected.
