### ISSUE TITLE
The e2e eventing flow breaks with Knative v0.4.0

### ISSUE THREAD

**Issue by abbi-gaurav** [kyma-project/kyma#3057]
**Description**
While upgrading Knative versions 0.4.0, it was discovered that the e2e eventing flow breaks down at the lambda trigger.
Kubeless throws the following error:

```
Function failed to execute: SyntaxError: Unexpected token s in JSON at position 4
    at JSON.parse (<anonymous>)
    at modExecute (/kubeless_rt/kubeless.js:83:29)
    at /kubeless_rt/kubeless.js:57:29
    at /kubeless/handler.js:2:20
    at ContextifyScript.Script.runInContext (vm.js:59:29)
    at ContextifyScript.Script.runInNewContext (vm.js:65:15)
    at app.all (/kubeless_rt/kubeless.js:156:20)
    at Layer.handle [as handle_request] (/kubeless_rt/node_modules/express/lib/router/layer.js:95:5)
    at next (/kubeless_rt/node_modules/express/lib/router/route.js:137:13)
    at next (/kubeless_rt/node_modules/express/lib/router/route.js:131:14)
```

Upon investigation, it was discovered that in Knative 0.4 the NATS provisioner has been updated to support CE. This has an impact now, that the message gets stored in the NATS Streaming in the following format.

```
{
  "headers": {
    "Content-Type": "application/json",
    "X-B3-Sampled": "1",
    "X-B3-Spanid": "9ddf5cf97c870d89",
    "X-B3-Traceid": "9ddf5cf97c870d89",
    "X-Request-Id": "0d31961a-d290-9594-a28a-48cba37f493d",
    "ce-knativehistory": "sample--external--solution-order-dot-created-v1.kyma-system.channels.cluster.local"
  },
    "payload": "eyJ7InNvdXJjZS1pZCI6InNhbXBsZS1leHRlcm5hbC1zb2x1dGlvbiIsImV2ZW50LXR5cGUiOiJvcmRlci5jcmVhdGVkIiwiZXZlbnQtdHlwZS12ZXJzaW9uIjoidjEiLCJldmVudC1pZCI6IjNkMmY2MzRmLThjMDctNGI4Yy1iMTdlLTM3YTJkMjRjN2JiZCIsImV2ZW50LXRpbWUiOiIyMDE4LTA1LTAyVDIyOjA4OjQxKzAwOjAwIiwiZGF0YSI6eyJvcmRlckNvZGUiOiIyIn0sIlNvdXJjZUlkRnJvbUhlYWRlciI6ZmFsc2UsImV4dGVuc2lvbnMiOnsidHJhY2UtY29udGV4dCI6eyJ4LWIzLWZsYWdzIjoiMCIsIngtYjMtcGFyZW50c3BhbmlkIjoiNzg2ZWIzZjBjOGRmYTU3MSIsIngtYjMtc2FtcGxlZCI6IjEiLCJ4LWIzLXNwYW5pZCI6IjE4YmFjMzEyYjU4MzlkMjMiLCJ4LWIzLXRyYWNlaWQiOiI3ZTRkY2Y5ZmI5ZGQ3NGQwIn19fSJ9"
}
```

The NATS Streaming dispatcher then extracts the headers and payload and send them as HTTP headers and payload.

The kubeless receives the payload expecting it to be a JSON and thus breaks down.

The payload is actually a base64 encoded version of:
```
{"{"source-id":"sample-external-solution","event-type":"order.created","event-type-version":"v1","event-id":"3d2f634f-8c07-4b8c-b17e-37a2d24c7bbd","event-time":"2018-05-02T22:08:41+00:00","data":{"orderCode":"2"},"SourceIdFromHeader":false,"extensions":{"trace-context":{"x-b3-flags":"0","x-b3-parentspanid":"786eb3f0c8dfa571","x-b3-sampled":"1","x-b3-spanid":"18bac312b5839d23","x-b3-traceid":"7e4dcf9fb9dd74d0"}}}"}
```

I do not see this being decoded in the dispatcher code
`contrib/natss/pkg/dispatcher/dispatcher/dispatcher.go`

**Update [2019-03-11]**
The flow in 0.4 separates the headers and payload into two message parts:

```
type Message struct {
	// Headers provide metadata about the message payload. All header keys
	// should be lowercase.
	Headers map[string]string `json:"headers,omitempty"`

	// Payload is the raw binary content of the message. The payload format is
	// often described by the 'content-type' header.
	Payload []byte `json:"payload,omitempty"`
}
```

The common Knative eventing APIs:

```
pkg/provisioners/message_receiver.go:147 
func (r *MessageReceiver) fromRequest(req *http.Request) (*Message, error) {}

pkg/provisioners/message_dispatcher.go:103
func (d *MessageDispatcher) executeRequest(url *url.URL, message *Message) (*Message, error) {}

#sample paylaod delivered to lambda
hi
{ 'event-type': undefined,
  'event-id': undefined,
  'event-time': undefined,
  'event-namespace': undefined,
  data:
   { 'source-id': 'dummy.source',
     'event-type': 'test-event-bus',
     'event-type-version': 'v1',
     'event-id': '8da7a5f4-75d9-4e99-998e-f149d69e369c',
     'event-time': '2018-11-02T22:08:41+00:00',
     data: { orderCode: '3', orderPrice: 123.4 },
     SourceIdFromHeader: false,
     extensions: { 'trace-context': [Object] } },

```

Perhaps we should update the publish to send headers and payload separately.

**AC**
- [x] E2E scenario works with Knative 0.4 changes.
- [x] Update the documentation in https://github.com/kyma-project/kyma/blob/master/docs/event-bus/docs
- [x] Update the examples if required.
- [x] Lambda gets triggered and `event.data` object contains the actual event payload.

**Comment by abbi-gaurav** [comment]
Please refer #3070.

**Comment by radufa** [comment]
I've done a dump of our request without any changes on our implementation:
```
curl -i -H "Content-Type:application/json" -X POST http://localhost:8080/v1/events -d '{"source-id": "external-application", "event-type": "test-event-bus", "event-type-version": "v1", "event-time": "2018-11-02T22:08:41+00:00", "data": {"event":{"customer":{"customerID": "1234", "uid": "rick.sanchez@mail.com"}}}}'
```
and the request sent to Kubeless by NATSS dispatcher:
```
{"source-id":"external-application","event-type":"test-event-bus","event-type-version":"v1","event-id":"b414f9b9-4c8d-4bfb-a481-fd31967fd68c","event-time":"2018-11-02T22:08:41+00:00","data":{"event":{"customer":{"customerID":"1234","uid":"rick.sanchez@mail.com"}}},"SourceIdFromHeader":false,"extensions":{"trace-context":{"x-b3-flags":"0","x-b3-sampled":"1","x-b3-spanid":"779a674dd7bec9ac","x-b3-traceid":"04c84f4e8d7807b1"}}}
```

**Comment by radufa** [comment]
After changes, publish send the following request to channel:
```
dump req:POST / HTTP/1.1
Host: external--application-test--event--bus-v1-channel-g85hk.kyma-system.svc.cluster.local
Content-Type: application/json
Event-Id: ce9a7dd3-2c31-4ba7-b74f-cf4d4f40ba82
Event-Time: 2018-11-02T22:08:41+00:00
Event-Type: test-event-bus
Event-Type-Version: v1
Source-Id: external-application
X-B3-Flags: 0
X-B3-Sampled: 1
X-B3-Spanid: 7a299f3306b8115a
X-B3-Traceid: 448096338b4c05bc

{"event":{"customer":{"customerID":"1234","uid":"rick.sanchez@mail.com"}}}
```

**Comment by radufa** [comment]
As a comparison, without knative, push send to lambda the following http request:
```
Content-Length: 74
Content-Type: application/json
Kyma-Event-Id: 5f249c8d-ab4b-4b47-a973-3b5f118cd8a1
Kyma-Event-Time: 2018-11-02T22:08:41+00:00
Kyma-Event-Type: test-event-bus
Kyma-Event-Type-Version: v1
nKyma-Source-Id: external-application
Kyma-Subscription: example-subscription
User-Agent: Go-http-client/1.1
X-B3-Flags: 0
X-B3-Parentspanid: 7072330b32b41917
X-B3-Sampled: 1
X-B3-Spanid: 7aa84bd79d24fed2
X-B3-Traceid: 5877867119168241
X-Envoy-Internal: true
X-Forwarded-For: 172.17.0.1
X-Forwarded-Proto: http
X-Request-Id: 4a0664e4-a4a6-97da-93c7-8bc45e8155c2

{"event":{"customer":{"customerID":"1234","uid":"rick.sanchez@mail.com"}}}"
```

**Comment by radufa** [comment]
The Kyma headers can be transmitted to lambda only if they are prefixed with "ce-".
In this case, the natss dispatcher send to lambda:
```
Send as CE headers:

{
"headers":
  {"Ce-Event-Id":"0e798b01-444f-4132-a107-22c2d0e2a939","Ce-Event-Time":"2018-11-02T22:08:41+00:00","Ce-Event-Type":"test-event-bus","Ce-Event-Type-Version":"v1","Ce-Source-Id":"external-application","Content-Type":"application/json","X-B3-Flags":"0","X-B3-Parentspanid":"41f0ff3837de6151","X-B3-Sampled":"1","X-B3-Spanid":"c8a37963d021f2f8","X-B3-Traceid":"7d2a701f50c6ddf2","X-Request-Id":"f94218ae-2ab6-9719-a472-9b322857fb05","ce-knativehistory":"external--application-test--event--bus-v1.kyma-system.channels.cluster.local"
  },
"payload":"
  {"event":{"customer":{"customerID":"1234","uid":"rick.sanchez@mail.com"}}}
}
```
