### ISSUE TITLE
core-console tests are failling

### ISSUE THREAD

**Issue by rakesh-garimella** [kyma-project/kyma#5055]
**Description**

The core console tests are failing and preventing from PR merges

**Expected result**

They should pass
**Actual result**
They are failling. Following is a snippet from logs
```
FAIL src/tests/catalog-ui-test.js (602.217s)
  ● Console

    console.log jest-setup.js:3
      Setting default timeout to 240 seconds
    console.log src/setup/namespace-manager.js:20
      Creating namespace service-catalog-ui-test...
    console.log src/commands/common.js:51
      Opening https://console.gkeint-pr-4606-t4wk03cbma.a.build.kyma-project.io
    console.log src/commands/console.js:14
      Trying to log in admin@kyma.cx via dex
    console.log src/commands/common.js:17
      Request failed:
      URL: https://console.gkeint-pr-4606-t4wk03cbma.a.build.kyma-project.io/luigi-core/auth/oidc/oidc-client.min.js 
      Method: GET
      Failure: net::ERR_ABORTED
    console.log src/utils/logging.js:36
      Request GET https://console.gkeint-pr-4606-t4wk03cbma.a.build.kyma-project.io/luigi-core/auth/oidc/oidc-client.min.js failed with message : net::ERR_ABORTED
    console.log src/tests/catalog-ui-test.js:109
      Check if `Testing bundle` is on the list
    console.log src/tests/catalog-ui-test.js:190
      Provision `Testing bundle` with `Minimal` plan
    console.log src/commands/catalog.js:81
      Create instance failed
    console.error src/utils/retry.js:8
      Error in retry attempt 1: Error: No node found for selector: [data-e2e-id="add-to-env"]
          at assert (/app/node_modules/puppeteer/lib/helper.js:231:11)
          at DOMWorld.click (/app/node_modules/puppeteer/lib/DOMWorld.js:366:5)
          at <anonymous>
        -- ASYNC --
          at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:110:27)
          at click (/app/src/commands/catalog.js:30:19)
          at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
          at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
          at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:114:21)
          at step (/app/src/commands/catalog.js:233:191)
          at /app/src/commands/catalog.js:233:361
          at <anonymous>
    console.log src/utils/retry.js:10
      Retrying... Attempt 2/5
    console.log src/commands/catalog.js:81
      Create instance failed
    console.error src/utils/retry.js:8
      Error in retry attempt 2: Error: No node found for selector: [data-e2e-id="add-to-env"]
          at assert (/app/node_modules/puppeteer/lib/helper.js:231:11)
          at DOMWorld.click (/app/node_modules/puppeteer/lib/DOMWorld.js:366:5)
          at <anonymous>
        -- ASYNC --
          at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:110:27)
          at click (/app/src/commands/catalog.js:30:19)
          at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
          at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
          at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:114:21)
          at step (/app/src/commands/catalog.js:233:191)
          at /app/src/commands/catalog.js:233:361
          at <anonymous>
    console.log src/utils/retry.js:10
      Retrying... Attempt 3/5
    console.log src/commands/catalog.js:81
      Create instance failed
    console.error src/utils/retry.js:8
      Error in retry attempt 3: Error: No node found for selector: [data-e2e-id="add-to-env"]
          at assert (/app/node_modules/puppeteer/lib/helper.js:231:11)
          at DOMWorld.click (/app/node_modules/puppeteer/lib/DOMWorld.js:366:5)
          at <anonymous>
        -- ASYNC --
          at Frame.<anonymous> (/app/node_modules/puppeteer/lib/helper.js:110:27)
          at click (/app/src/commands/catalog.js:30:19)
          at tryCatch (/app/node_modules/regenerator-runtime/runtime.js:62:40)
          at Generator.invoke [as _invoke] (/app/node_modules/regenerator-runtime/runtime.js:296:22)
          at Generator.prototype.(anonymous function) [as next] (/app/node_modules/regenerator-runtime/runtime.js:114:21)
          at step (/app/src/commands/catalog.js:233:191)
          at /app/src/commands/catalog.js:233:361
          at <anonymous>
    console.log src/utils/retry.js:10
```
more details:
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/4606/pre-master-kyma-gke-central-connector/1154711966367879169

https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/pr-logs/pull/kyma-project_kyma/4606/pre-master-kyma-gke-minio-gateway/1154711966359490562

**Comment by dariadomagala** [comment]
It didn't fail even once since July 26, so it's probably an issue that has already been fixed by something else. 

I will keep this issue open to keep track, and if it won't fail again anytime soon I will close it.

**Comment by sjanota** [comment]
Never happened again
