### ISSUE TITLE
Console basic tests › Delete Application is randomly failing

### ISSUE THREAD

**Issue by michal-hudy** [kyma-project/kyma#6686]
**Description**

Mostly Console tests are failing because:
```
● Console basic tests › Delete Application

    TimeoutError: waiting for XPath "//h1[contains(string(), "General Information")]" failed: timeout 30000ms exceeded

      179 |     );
      180 |     frame.waitForXPath(`//td[contains(string(), "${config.testApp}")]`);
    > 181 |     frame.waitForXPath(`//h1[contains(string(), "General Information")]`);
          |           ^
      182 | 
      183 |     frame.waitForSelector('.fd-breadcrumb__link');
      184 |     frame.click('.fd-breadcrumb__link');

      at new WaitTask (node_modules/puppeteer/lib/DOMWorld.js:549:28)
      at DOMWorld._waitForSelectorOrXPath (node_modules/puppeteer/lib/DOMWorld.js:478:22)
      at DOMWorld.waitForXPath (node_modules/puppeteer/lib/DOMWorld.js:441:17)
      at Frame.waitForXPath (node_modules/puppeteer/lib/FrameManager.js:642:47)
      at Frame.<anonymous> (node_modules/puppeteer/lib/helper.js:112:23)
      at waitForXPath (src/tests/console-basic-test.js:181:11)
      at tryCatch (node_modules/regenerator-runtime/runtime.js:62:40)
      at Generator.invoke [as _invoke] (node_modules/regenerator-runtime/runtime.js:296:22)
      at Generator.prototype.(anonymous function) [as next] (node_modules/regenerator-runtime/runtime.js:114:21)
      at step (src/tests/console-basic-test.js:33:191)
      at src/tests/console-basic-test.js:33:361
```

They don't fail always, but when you look at https://testgrid.k8s.io/kyma-postsubmit#post-master-kyma-gke-upgrade&exclude-non-failed-tests= it failed even 4 times in a row recently. I don't know if it is related to test or we have some problems in UI. Also, remember that tests are restarted if the first attempt fails, so in fact, it failed 8 times in a row...

**Expected result**

UI tests are stable

**Actual result**

Analyze recent core-console failures on master: https://testgrid.k8s.io/kyma-postsubmit

**Steps to reproduce**

Trigger integration pipeline

**Troubleshooting**

**Comment by dariadomagala** [comment]
Tests are temporarily disabled. Fix and enable them.
