### ISSUE TITLE
Pre upgrade hook for event-bus-mesh-namespaces-migration breaks 

### ISSUE THREAD

**Issue by sayanh** [kyma-project/kyma#7757]
**Description**

`mesh-namespaces-migration` pre upgrade job fails with:
```
k logs -n kyma-system event-bus-mesh-namespaces-migration-mesh-namespaces-migratbhkfm
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x14c5be6]

goroutine 1 [running]:
main.(*serviceInstanceManager).populateServiceInstances(0xc0000da280, 0xc000576080, 0x5, 0x8, 0x1, 0xc00047cc6a)
        /workspace/go/src/github.com/kyma-project/kyma/components/event-bus/cmd/mesh-namespaces-migration/serviceinstance.go:94 +0x2d6
main.newServiceInstanceManager(0x1c1a1c0, 0xc0004b33c0, 0x1c17580, 0xc0004b2ca0, 0x1bf15a0, 0xc0000dc250, 0xc000576080, 0x5, 0x8, 0x0, ...)
        /workspace/go/src/github.com/kyma-project/kyma/components/event-bus/cmd/mesh-namespaces-migration/serviceinstance.go:58 +0xc4
main.main()
        /workspace/go/src/github.com/kyma-project/kyma/components/event-bus/cmd/mesh-namespaces-migration/main.go:56 +0x1d2
```

https://github.com/kyma-project/kyma/blob/release-1.11/components/event-bus/cmd/mesh-namespaces-migration/serviceinstance.go#L94 breaks as the serviceinstances present had a specification as follows:
```
apiVersion: servicecatalog.k8s.io/v1beta1
kind: ServiceInstance
metadata:
  annotations:
    tags: ""
  creationTimestamp: "2020-03-23T10:23:36Z"
  finalizers:
  - kubernetes-incubator/service-catalog
  generation: 2
  labels:
    servicecatalog.k8s.io/spec.clusterServiceClassRef.name: 76c64259231ed32473d6da493f3ef7e2eace7c8e23cf6b3b0155a0b4
    servicecatalog.k8s.io/spec.clusterServicePlanRef.name: 5b10302882037cea4a596cb5a03851c0e3fdf4d9c9258d2685fb1c9b
  name: commerce-mock-deep-convert
  namespace: hasselhoff
  resourceVersion: "1093441"
  selfLink: /apis/servicecatalog.k8s.io/v1beta1/namespaces/hasselhoff/serviceinstances/commerce-mock-deep-convert
  uid: 4b829ac3-e36f-4585-bcca-bfd1b6e27bc1
spec:
  clusterServiceClassExternalName: commerce-mock
  clusterServiceClassRef:
    name: faebbe18-0a84-11e9-ab14-d663bd873d98
  clusterServicePlanExternalName: default
  clusterServicePlanRef:
    name: 0c712d43-b1e6-480s-9fe5-8e1d552aa6a1
  externalID: 59ea6671-506f-4c96-aef6-fc6d8ad19742
  parameters: {}
  updateRequests: 0
  userInfo:
    groups:
    - system:serviceaccounts
    - system:serviceaccounts:kyma-system
    - system:authenticated
    uid: ef7319ad-0941-4bae-b645-d0a9c43a1e39
    username: system:serviceaccount:kyma-system:service-catalog-controller-manager
```

This SI had `clusterServiceClassRef` but no `serviceClassRef`.

**Expected result**

Upgrade job should be tolerant of this. As per ServiceInstance spec, it could either have `clusterServiceClassRef` or `serviceClassRef`

**Actual result**

Upgrade job fails.

**Steps to reproduce**

Create an SI with clusterServiceClassRef and upgrade Kyma.

**Comment by sayanh** [comment]
For an eventing ServiceInstance, `serviceClassRef` is possible and not a `clusterServiceClassRef`. Hence I think, this migration job should only be interested in `serviceClassRef`.
