### ISSUE TITLE
Event Service Dumped on sending events from commerce

### ISSUE THREAD

**Issue by anishj0shi** [kyma-project/kyma#7888]
On Sending Events from CCv2, event publishing failed. 

**This was fixed on restarting the Event-service pod**
**This issue is intermittent.**

```
kubectl logs -n kyma-integration commerce-event-service-79bb55d79-kwjxt commerce-event-service
2020/04/02 05:43:42 http: panic serving 127.0.0.1:55032: invalid WriteHeader code 0
goroutine 117957 [running]:
net/http.(*conn).serve.func1(0xc0005ea140)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x1199920, 0xc000240070)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
net/http.checkWriteHeaderCode(...)
	/usr/local/go/src/net/http/server.go:1093
net/http.(*response).WriteHeader(0xc00008a1c0, 0x0)
	/usr/local/go/src/net/http/server.go:1127 +0x607
github.com/kyma-project/kyma/components/event-service/internal/externalapi.writeJSONResponse(0x15341e0, 0xc00008a1c0, 0xc0000ace70)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/internal/externalapi/genericeventhandler.go:138 +0x250
github.com/kyma-project/kyma/components/event-service/internal/externalapi.getEventsHandler.func1(0x15341e0, 0xc00008a1c0, 0xc000444800)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/internal/externalapi/genericeventhandler.go:97 +0x565
net/http.HandlerFunc.ServeHTTP(0xc000491700, 0x15341e0, 0xc00008a1c0, 0xc000444800)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/kyma-project/kyma/components/event-service/internal/externalapi.(*maxBytesHandler).ServeHTTP(0xc0002c9b80, 0x15341e0, 0xc00008a1c0, 0xc000444800)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/internal/externalapi/genericeventhandler.go:34 +0xe0
github.com/kyma-project/kyma/components/event-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001b8000, 0x15341e0, 0xc00008a1c0, 0xc000444600)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/vendor/github.com/gorilla/mux/mux.go:210 +0xe3
net/http.serverHandler.ServeHTTP(0xc0000b88f0, 0x15341e0, 0xc00008a1c0, 0xc000444600)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0005ea140, 0x153d1a0, 0xc00040e700)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
2020/04/02 05:43:42 http: panic serving 127.0.0.1:55046: invalid WriteHeader code 0
goroutine 117966 [running]:
net/http.(*conn).serve.func1(0xc0005ea1e0)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x1199920, 0xc0004900c0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
net/http.checkWriteHeaderCode(...)
	/usr/local/go/src/net/http/server.go:1093
net/http.(*response).WriteHeader(0xc00008a460, 0x0)
	/usr/local/go/src/net/http/server.go:1127 +0x607
github.com/kyma-project/kyma/components/event-service/internal/externalapi.writeJSONResponse(0x15341e0, 0xc00008a460, 0xc0000ad6d0)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/internal/externalapi/genericeventhandler.go:138 +0x250
github.com/kyma-project/kyma/components/event-service/internal/externalapi.getEventsHandler.func1(0x15341e0, 0xc00008a460, 0xc000444d00)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/internal/externalapi/genericeventhandler.go:97 +0x565
net/http.HandlerFunc.ServeHTTP(0xc000491700, 0x15341e0, 0xc00008a460, 0xc000444d00)
	/usr/local/go/src/net/http/server.go:1995 +0x44
github.com/kyma-project/kyma/components/event-service/internal/externalapi.(*maxBytesHandler).ServeHTTP(0xc0002c9b80, 0x15341e0, 0xc00008a460, 0xc000444d00)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/internal/externalapi/genericeventhandler.go:34 +0xe0
github.com/kyma-project/kyma/components/event-service/vendor/github.com/gorilla/mux.(*Router).ServeHTTP(0xc0001b8000, 0x15341e0, 0xc00008a460, 0xc000444b00)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/vendor/github.com/gorilla/mux/mux.go:210 +0xe3
net/http.serverHandler.ServeHTTP(0xc0000b88f0, 0x15341e0, 0xc00008a460, 0xc000444b00)
	/usr/local/go/src/net/http/server.go:2774 +0xa8
net/http.(*conn).serve(0xc0005ea1e0, 0x153d1a0, 0xc00040fe00)
	/usr/local/go/src/net/http/server.go:1878 +0x851
created by net/http.(*Server).Serve
	/usr/local/go/src/net/http/server.go:2884 +0x2f4
2020/04/02 06:28:25 http: panic serving 127.0.0.1:44742: invalid WriteHeader code 0
goroutine 118656 [running]:
net/http.(*conn).serve.func1(0xc000256460)
	/usr/local/go/src/net/http/server.go:1769 +0x139
panic(0x1199920, 0xc0002404d0)
	/usr/local/go/src/runtime/panic.go:522 +0x1b5
net/http.checkWriteHeaderCode(...)
	/usr/local/go/src/net/http/server.go:1093
net/http.(*response).WriteHeader(0xc00021a540, 0x0)
	/usr/local/go/src/net/http/server.go:1127 +0x607
github.com/kyma-project/kyma/components/event-service/internal/externalapi.writeJSONResponse(0x15341e0, 0xc00021a540, 0xc000240110)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/internal/externalapi/genericeventhandler.go:138 +0x250
github.com/kyma-project/kyma/components/event-service/internal/externalapi.getEventsHandler.func1(0x15341e0, 0xc00021a540, 0xc000612f00)
	/workspace/go/src/github.com/kyma-project/kyma/components/event-service/internal/externalapi/genericeventhandler.go:97 +0x565
```

**Comment by sayanh** [comment]
Kyma version: 1.11-rc2

It is found the event-service pod did not have any restarts:
```
➜ k get application commerce
NAME       AGE
commerce   7d4h

➜ k get po -n kyma-integration -lapp=commerce-event-service
NAME                                     READY   STATUS    RESTARTS   AGE
commerce-event-service-79bb55d79-kwjxt   2/2     Running   0          7d4h
```
Maybe the container `commerce-event-service` was restarted. As the events are gone, it can't be concluded.

Pod description is as follows:
```
➜ k describe po -n kyma-integration commerce-event-service-79bb55d79-kwjxt
Name:           commerce-event-service-79bb55d79-kwjxt
Namespace:      kyma-integration
Priority:       0
Node:           shoot--kyma-dev--fb44825-cpu-worker-0-d5cdfbc99-f6t62/10.250.0.5
Start Time:     Tue, 31 Mar 2020 11:36:17 +0200
Labels:         app=commerce-event-service
                kyma-alerts=enabled
                kyma-grafana=enabled
                pod-template-hash=79bb55d79
                release=commerce
                security.istio.io/tlsMode=istio
Annotations:    cni.projectcalico.org/podIP: 100.96.2.150/32
                cni.projectcalico.org/podIPs: 100.96.2.150/32
                kubernetes.io/limit-ranger:
                  LimitRanger plugin set: memory request for container commerce-event-service; memory limit for container commerce-event-service
                kubernetes.io/psp: gardener.privileged
                sidecar.istio.io/inject: true
                sidecar.istio.io/status:
                  {"version":"b5faac9e6b02231b7db3b29487392a395f1c85c746bf62dc8cb660444af6e0d9","initContainers":["istio-init"],"containers":["istio-proxy"]...
Status:         Running
IP:             100.96.2.150
IPs:            <none>
Controlled By:  ReplicaSet/commerce-event-service-79bb55d79
Init Containers:
  istio-init:
    Container ID:  docker://7f9e646bd8a47a5572699511d7a35d5d7ecd393c9e544dd34e1d6877ffcb7a09
    Image:         docker.io/istio/proxyv2:1.4.6-distroless
    Image ID:      docker-pullable://istio/proxyv2@sha256:6093b6eed8aa67e1d52172a3b748eead0d11a76288ff14032fcc1fd664bb70f6
    Port:          <none>
    Host Port:     <none>
    Command:
      istio-iptables
      -p
      15001
      -z
      15006
      -u
      1337
      -m
      REDIRECT
      -i
      *
      -x

      -b
      *
      -d
      15020
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 31 Mar 2020 11:36:20 +0200
      Finished:     Tue, 31 Mar 2020 11:36:21 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  50Mi
    Requests:
      cpu:        10m
      memory:     10Mi
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from commerce-event-service-token-qj54s (ro)
Containers:
  commerce-event-service:
    Container ID:  docker://1a90410b38c85ef2eefdabc993762a3affde71e14462d02be46646afe1718869
    Image:         eu.gcr.io/kyma-project/event-service:cd9874af
    Image ID:      docker-pullable://eu.gcr.io/kyma-project/event-service@sha256:bf3de75f8cc58107724465cfccca447612fb28b27bfbee310de03118f5c7dbf6
    Port:          8081/TCP
    Host Port:     0/TCP
    Args:
      /eventservice
      --externalAPIPort=8081
      --eventMeshURL=http://commerce.kyma-integration
      --eventsTargetURLV1=http://event-publish-service.kyma-system.svc.cluster.local:8080/v1/events
      --eventsTargetURLV2=http://event-publish-service.kyma-system.svc.cluster.local:8080/v2/events
      --maxRequestSize=65536
      --requestTimeout=10
      --requestLogging=false
      --sourceId=commerce
    State:          Running
      Started:      Tue, 31 Mar 2020 11:36:23 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      memory:  96Mi
    Requests:
      memory:     32Mi
    Liveness:     http-get http://:15020/app-health/commerce-event-service/livez delay=10s timeout=1s period=10s #success=1 #failure=3
    Readiness:    http-get http://:15020/app-health/commerce-event-service/readyz delay=5s timeout=1s period=5s #success=1 #failure=3
    Environment:  <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from commerce-event-service-token-qj54s (ro)
  istio-proxy:
    Container ID:  docker://6ea387446b6c29f12fd3232b416f6fbff5ed93ac6fceb6273517c9555b816dfc
    Image:         docker.io/istio/proxyv2:1.4.6-distroless
    Image ID:      docker-pullable://istio/proxyv2@sha256:6093b6eed8aa67e1d52172a3b748eead0d11a76288ff14032fcc1fd664bb70f6
    Port:          15090/TCP
    Host Port:     0/TCP
    Args:
      proxy
      sidecar
      --domain
      $(POD_NAMESPACE).svc.cluster.local
      --configPath
      /etc/istio/proxy
      --binaryPath
      /usr/local/bin/envoy
      --serviceCluster
      commerce-event-service.$(POD_NAMESPACE)
      --drainDuration
      45s
      --parentShutdownDuration
      1m0s
      --discoveryAddress
      istio-pilot.istio-system:15011
      --zipkinAddress
      zipkin.kyma-system:9411
      --proxyLogLevel=warning
      --proxyComponentLogLevel=misc:error
      --connectTimeout
      10s
      --proxyAdminPort
      15000
      --concurrency
      2
      --controlPlaneAuthPolicy
      MUTUAL_TLS
      --dnsRefreshRate
      300s
      --statusPort
      15020
      --applicationPorts
      8081
      --trust-domain=cluster.local
    State:          Running
      Started:      Tue, 31 Mar 2020 11:36:24 +0200
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     200m
      memory:  128Mi
    Requests:
      cpu:      20m
      memory:   32Mi
    Readiness:  http-get http://:15020/healthz/ready delay=1s timeout=1s period=2s #success=1 #failure=30
    Environment:
      POD_NAME:                          commerce-event-service-79bb55d79-kwjxt (v1:metadata.name)
      POD_NAMESPACE:                     kyma-integration (v1:metadata.namespace)
      INSTANCE_IP:                        (v1:status.podIP)
      SERVICE_ACCOUNT:                    (v1:spec.serviceAccountName)
      HOST_IP:                            (v1:status.hostIP)
      ISTIO_META_POD_PORTS:              [
                                             {"name":"http-api-port","containerPort":8081,"protocol":"TCP"}
                                         ]
      ISTIO_META_CLUSTER_ID:             Kubernetes
      ISTIO_META_POD_NAME:               commerce-event-service-79bb55d79-kwjxt (v1:metadata.name)
      ISTIO_META_CONFIG_NAMESPACE:       kyma-integration (v1:metadata.namespace)
      SDS_ENABLED:                       false
      ISTIO_META_INTERCEPTION_MODE:      REDIRECT
      ISTIO_META_INCLUDE_INBOUND_PORTS:  8081
      ISTIO_METAJSON_ANNOTATIONS:        {"kubernetes.io/limit-ranger":"LimitRanger plugin set: memory request for container commerce-event-service; memory limit for container commerce-event-service","kubernetes.io/psp":"gardener.privileged","sidecar.istio.io/inject":"true"}

      ISTIO_METAJSON_LABELS:             {"app":"commerce-event-service","kyma-alerts":"enabled","kyma-grafana":"enabled","pod-template-hash":"79bb55d79","release":"commerce"}

      ISTIO_META_WORKLOAD_NAME:          commerce-event-service
      ISTIO_META_OWNER:                  kubernetes://apis/apps/v1/namespaces/kyma-integration/deployments/commerce-event-service
      ISTIO_META_MESH_ID:                cluster.local
      ISTIO_KUBE_APP_PROBERS:            {"/app-health/commerce-event-service/livez":{"path":"/v1/health","port":8081,"scheme":"HTTP"},"/app-health/commerce-event-service/readyz":{"path":"/v1/health","port":8081,"scheme":"HTTP"}}
    Mounts:
      /etc/certs/ from istio-certs (ro)
      /etc/istio/proxy from istio-envoy (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from commerce-event-service-token-qj54s (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  commerce-event-service-token-qj54s:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  commerce-event-service-token-qj54s
    Optional:    false
  istio-envoy:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  istio-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  istio.commerce-event-service
    Optional:    true
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>

```

Steps to reproduce: unknown

Reason: Most probably the reason is the unhandled error in:
https://github.com/kyma-project/kyma/blob/release-1.11/components/event-service/internal/externalapi/genericeventhandler.go#L97


PR https://github.com/kyma-project/kyma/pull/7951/files solves the error handling
