### ISSUE TITLE
Console Smoke Tests Renders applications fails

### ISSUE THREAD

**Issue by rafalpotempa** [kyma-project/kyma#9961]
**Failure log**
```log
        <failure message="Timed out retrying: Expected to find content: &apos;Applications/Systems&apos; within the element: &lt;body&gt; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying: Expected to find content: 'Applications/Systems' within the element: <body> but never did.
      at Context.eval (https://console.gkeint-commit-94ac5eff-iuqc375hp4.a.build.kyma-project.io/__cypress/tests?p=tests/console-smoke-tests.spec.js:73:144)]]></failure>
```

**Job execution logs:**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-integration/1328263533271453697

**Another logs with more complex description:**
https://status.build.kyma-project.io/view/gcs/kyma-prow-logs/logs/post-master-kyma-gke-ver1_17_12-integration/1328263533275648000

```log
 > ui-tests@ test:cluster /usr/src/app
  > $(npm bin)/cypress run --quiet --browser chrome --headless --reporter junit --reporter-options mochaFile=artifacts/cypress-run.xml,toConsole=true
  
  [?25l[09:37:48]  Verifying Cypress can run /root/.cache/Cypress/4.12.1/Cypress [started]
  [09:37:56]  Verifying Cypress can run /root/.cache/Cypress/4.12.1/Cypress [completed]
  [?25hOne login method detected, trying to login using email...
  <?xml version="1.0" encoding="UTF-8"?>
  <testsuites name="Mocha Tests" time="138.571" tests="7" failures="1">
    <testsuite name="Root Suite" timestamp="2020-11-16T09:38:28" tests="0" file="tests/console-smoke-tests.spec.js" failures="0" time="0">
    </testsuite>
    <testsuite name="Console Smoke Tests" timestamp="2020-11-16T09:38:28" tests="7" failures="1" time="138.571">
      <testcase name="Console Smoke Tests Renders navigation nodes" time="20.371" classname="Renders navigation nodes">
      </testcase>
      <testcase name="Console Smoke Tests Renders namespaces details" time="17.593" classname="Renders namespaces details">
      </testcase>
      <testcase name="Console Smoke Tests Renders deployments" time="15" classname="Renders deployments">
      </testcase>
      <testcase name="Console Smoke Tests Renders applications" time="0" classname="Renders applications">
        <failure message="Timed out retrying: Expected to find content: &apos;Applications/Systems&apos; within the element: &lt;body&gt; but never did." type="AssertionError"><![CDATA[AssertionError: Timed out retrying: Expected to find content: 'Applications/Systems' within the element: <body> but never did.
      at Context.eval (https://console.gkeint-commit-94ac5eff-iuqc375hp4.a.build.kyma-project.io/__cypress/tests?p=tests/console-smoke-tests.spec.js:73:144)]]></failure>
      </testcase>
      <testcase name="Console Smoke Tests Renders service catalog" time="37.321" classname="Renders service catalog">
      </testcase>
      <testcase name="Console Smoke Tests Renders functions" time="13.49" classname="Renders functions">
      </testcase>
      <testcase name="Console Smoke Tests Renders docs" time="34.796" classname="Renders docs">
      </testcase>
    </testsuite>
  </testsuites>
  npm ERR! code ELIFECYCLE
  npm ERR! errno 1
  npm ERR! ui-tests@ test:cluster: `$(npm bin)/cypress run --quiet --browser chrome --headless --reporter junit --reporter-options mochaFile=artifacts/cypress-run.xml,toConsole=true`
  npm ERR! Exit status 1
  npm ERR! 
  npm ERR! Failed at the ui-tests@ test:cluster script.
  npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
  
  npm ERR! A complete log of this run can be found in:
  npm ERR!     /root/.npm/_logs/2020-11-16T09_41_47_001Z-debug.log
  [?25hcode is 1
  killing pilot-agent...
```

**Comment by IamRohitMittal** [comment]
@rafalpotempa Did you find the fix for it?
